import type {EmailIntelligenceResult,EmailMention,EmailMetadata} from '../../types/command';

export class EmailValidationError extends Error {}
const providerMap:Record<string,{provider:string;mx:string[]}>= {'gmail.com':{provider:'Google / Gmail',mx:['gmail-smtp-in.l.google.com']},'outlook.com':{provider:'Microsoft Outlook / Hotmail',mx:['outlook-com.olc.protection.outlook.com']},'hotmail.com':{provider:'Microsoft Outlook / Hotmail',mx:['outlook-com.olc.protection.outlook.com']},'yahoo.com':{provider:'Yahoo Mail',mx:['mta5.am0.yahoodns.net']},'proton.me':{provider:'Proton Mail',mx:['mail.protonmail.ch']},'icloud.com':{provider:'Apple iCloud Mail',mx:['mx01.mail.icloud.com']},'zoho.com':{provider:'Zoho Mail',mx:['mx.zoho.com']}};
export function maskEmail(value:string){const [local,domain]=value.split('@');return `${local?.slice(0,1)??''}${'*'.repeat(Math.max(3,(local?.length??1)-1))}@${domain??''}`}
export function normalizeEmail(raw:string):EmailMetadata {
 const input=raw.trim();const at=input.lastIndexOf('@');if(at<1||at!==input.indexOf('@'))throw new EmailValidationError('Format email tidak valid. Gunakan local@domain.');
 const local=input.slice(0,at).toLowerCase(),unicodeDomain=input.slice(at+1).toLowerCase().replace(/\.$/,'');let domain='';
 try{domain=new URL(`http://${unicodeDomain}`).hostname}catch{throw new EmailValidationError('Domain email tidak valid.')}
 if(local.length>64||!local||local.startsWith('.')||local.endsWith('.')||local.includes('..')||!/[.]/.test(domain)||!/^[a-z0-9.!#$%&'*+/=?^_`{|}~-]+$/i.test(local)||!domain.split('.').every(x=>/^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/i.test(x)))throw new EmailValidationError('Format email tidak valid. Gunakan local@domain.');
 const known=providerMap[domain];return {raw,normalized:`${local}@${domain}`,localPart:local,domain,unicodeDomain,validFormat:true,mxStatus:known?'DETECTED':'NOT CHECKED',mxHosts:known?.mx??[],mailProvider:known?.provider??'Unknown / requires configured DNS adapter'};
}
const now=()=>new Date().toISOString();
function publicMentions():EmailMention[]{return []}
export async function createEmailIntelligence(raw:string,mode:EmailIntelligenceResult['mode']='lookup'):Promise<EmailIntelligenceResult>{const startedAt=now(),metadata=normalizeEmail(raw),all=publicMentions();const mentions=mode==='documents'?all.filter(x=>x.category==='DOCUMENT'):mode==='web'?all.filter(x=>x.category!=='DOCUMENT'):all;const completedAt=now();const exposure={status:'Not checked' as const,provider:'No lawful exposure provider configured',lawful:false,records:[],note:'Exposure lookup is disabled until a lawful provider is configured. NOT CHECKED is never converted to “not detected”. Login, password-reset probing, OTP, inbox access, and account enumeration are not permitted.'};const confidence=35+(metadata.mxStatus==='DETECTED'?20:0);return {kind:'email',targetType:'email',target:metadata.normalized,mode,metadata,mentions,exposure,mocked:false,provider:'EMAIL & GOOGLE PUBLIC FOOTPRINT · syntax and configured public-provider metadata',disclaimer:'Public and authorized sources only. Address masked by default. INBOX ACCESS: NOT PERMITTED · PASSWORD-RESET PROBING: NOT PERMITTED · PRIVACY PROTECTION: ACTIVE.',runId:`EMAIL-${Date.now().toString(36).toUpperCase()}`,startedAt,completedAt,durationMs:Math.max(1,Date.parse(completedAt)-Date.parse(startedAt)),stages:['FORMAT VALIDATION','PROVIDER IDENTIFICATION','EXACT PUBLIC REFERENCES','PUBLIC DOCUMENTS','PUBLIC PROFESSIONAL DIRECTORIES','PUBLIC GIT ATTRIBUTION','GOOGLE PUBLIC','EXPOSURE POLICY'].map((label,i)=>({id:`EMAIL-S-${i}`,label,status:'complete' as const})),findings:[{id:'EMAIL-F-01',category:'EMAIL',label:'Masked normalized address',value:maskEmail(metadata.normalized),entityType:'EMAIL',provenance:{id:'NORMALIZE-01',source:'Pegasus email parser',retrievedAt:completedAt,method:'Local syntax validation only; no authentication endpoint',confidence:'HIGH'}}],relationships:[],timeline:[],confidence:{score:confidence,factors:[{label:'Valid syntax (not proof of account existence)',impact:35},{label:'Configured provider metadata',impact:metadata.mxStatus==='DETECTED'?20:0},{label:'No ownership inference',impact:0}]},pivots:[{id:'EMAIL-P-01',title:'EXACT PUBLIC REFERENCES',reason:'Search the exact supplied address only through a configured lawful public index.',expectedOutput:'Public pages and documents with source URLs',dataSource:'Configured public index',confidence:50,estimatedCost:'LOW',command:`email references ${metadata.normalized}`,caseContext:'CASE-2026-001',status:'READY'}]};}
