import type {Finding,PivotRecommendation,SearchHit,SearchIntelligenceResult} from '../../types/command';

type IndexedRecord=Omit<SearchHit,'id'|'matchedTerms'|'score'> & {keywords:string[]};
const index:IndexedRecord[]=[
 {title:'Indonesia Digital Economy Outlook',url:'https://example.com/research/indonesia-digital-economy',displayUrl:'example.com / research',snippet:'Public research summary covering Indonesia\'s digital economy, technology adoption, and online services.',source:'WEB',keywords:['indonesia','digital','economy','technology','teknologi','research']},
 {title:'Open Data Indonesia — Public Dataset Catalogue',url:'https://example.org/open-data/indonesia',displayUrl:'example.org / open-data',snippet:'An indexed catalogue describing public datasets, government statistics, and reusable civic information.',source:'WEB',keywords:['indonesia','open','data','government','public','dataset']},
 {title:'Cybersecurity Awareness for Organizations',url:'https://example.net/guides/cybersecurity-awareness',displayUrl:'example.net / guides',snippet:'A public defensive guide for improving organizational security awareness and incident reporting.',source:'WEB',keywords:['cybersecurity','security','organization','defensive','guide']},
 {title:'Technology Community Announces Public Workshop',url:'https://example.com/news/technology-workshop',displayUrl:'example.com / news',snippet:'A community technology workshop will discuss open-source tools, digital literacy, and responsible research.',source:'NEWS',publishedAt:'2026-08-29',keywords:['technology','teknologi','community','workshop','open-source','digital']},
 {title:'New Public Data Initiative Launched in Jakarta',url:'https://example.org/news/jakarta-public-data',displayUrl:'example.org / news',snippet:'The initiative focuses on accessible public information and collaboration with researchers in Jakarta.',source:'NEWS',publishedAt:'2026-08-24',keywords:['jakarta','indonesia','public','data','research']},
 {title:'Example Organization Publishes Annual Report',url:'https://example.net/news/annual-report',displayUrl:'example.net / news',snippet:'The organization released a public annual report with governance, program, and operational highlights.',source:'NEWS',publishedAt:'2026-08-18',keywords:['example','organization','annual','report','public']},
];

const normalize=(value:string)=>value.toLocaleLowerCase('id-ID').normalize('NFKD').replace(/[^a-z0-9]+/g,' ').trim();
export function searchLocalIndex(query:string,mode:'search'|'web'|'news'='search',limit=20):SearchIntelligenceResult{
 const clean=query.trim();if(!clean)throw new Error('Masukkan kata kunci pencarian. Contoh: search "teknologi indonesia"');
 const terms=[...new Set(normalize(clean).split(' ').filter(term=>term.length>1))];
 const sourceFilter=mode==='web'?'WEB':mode==='news'?'NEWS':'ALL';
 const hits=index.map((record,position)=>{const haystack=normalize(`${record.title} ${record.snippet} ${record.keywords.join(' ')}`);const matchedTerms=terms.filter(term=>haystack.includes(term));const exact=normalize(record.title).includes(normalize(clean));const score=Math.min(99,35+matchedTerms.length*18+(exact?20:0)-position);return {...record,id:`SEARCH-${position+1}`,matchedTerms,score};}).filter(hit=>(sourceFilter==='ALL'||hit.source===sourceFilter)&&hit.matchedTerms.length>0).sort((a,b)=>b.score-a.score).slice(0,Math.min(Math.max(limit,1),20));
 const now=new Date().toISOString();
 const findings:Finding[]=hits.map(hit=>({id:`F-${hit.id}`,category:hit.source,label:hit.title,value:hit.url,entityType:'URL',provenance:{id:`SRC-${hit.id}`,source:'Pegasus Frontend Demo Index',retrievedAt:now,method:'Local full-text keyword matching',confidence:hit.score>=70?'HIGH':hit.score>=50?'MEDIUM':'LOW',sourceUrl:hit.url}}));
 const pivots:PivotRecommendation[]=[{id:'P-SEARCH-1',title:'REFINE WEB SEARCH',reason:'Narrow the current query to indexed web pages.',expectedOutput:'Web references ranked by keyword match',dataSource:'Frontend demo index',confidence:85,estimatedCost:'LOW',caseContext:'ACTIVE CASE',command:`web "${clean}"`,status:'READY'},{id:'P-SEARCH-2',title:'REFINE NEWS SEARCH',reason:'Limit the current query to indexed news items.',expectedOutput:'Dated public news references',dataSource:'Frontend demo index',confidence:85,estimatedCost:'LOW',caseContext:'ACTIVE CASE',command:`news "${clean}"`,status:'READY'}];
 return {kind:'search',targetType:'query',target:clean,mode,sourceFilter,hits,totalIndexed:index.filter(item=>sourceFilter==='ALL'||item.source===sourceFilter).length,mocked:true,provider:'PEGASUS FRONTEND DEMO INDEX',disclaimer:'Hasil berasal dari indeks demo lokal di browser, bukan pencarian internet langsung.',runId:`RUN-SEARCH-${Date.now().toString(36).toUpperCase()}`,startedAt:now,completedAt:now,durationMs:Math.max(12,terms.length*7),stages:[{id:'S-1',label:'NORMALIZE QUERY',status:'complete'},{id:'S-2',label:'FILTER SOURCE',status:'complete'},{id:'S-3',label:'RANK MATCHES',status:'complete'}],findings,relationships:[],timeline:[{id:'T-SEARCH',at:now,type:'SEARCH',label:`Frontend index searched for “${clean}”`,sourceId:'LOCAL-INDEX',confidence:100}],confidence:{score:hits.length?88:100,factors:[{label:'Deterministic local index',impact:35},{label:'Visible keyword matching',impact:25},{label:'No live internet provider',impact:-20}]},pivots};
}
