const buckets=new Map();
function rateLimited(key){const now=Date.now(),windowMs=60_000,max=12;const hits=(buckets.get(key)||[]).filter(t=>now-t<windowMs);hits.push(now);buckets.set(key,hits);return hits.length>max}
function normalize(raw){if(typeof raw!=='string'||/[A-Za-z]/.test(raw)||/[^\d+().\s-]/.test(raw))throw new Error('Invalid Indonesian phone number');let digits=raw.replace(/\D/g,'');if(digits.startsWith('62'))digits=`0${digits.slice(2)}`;if(!/^08\d{8,11}$/.test(digits))throw new Error('Invalid Indonesian mobile format');return {local:digits,e164:`+62${digits.slice(1)}`}}
const safeUrl=value=>{try{const url=new URL(value);return url.protocol==='https:'&&!['localhost','127.0.0.1','169.254.169.254'].includes(url.hostname)&&!/^10\.|^192\.168\.|^172\.(1[6-9]|2\d|3[01])\./.test(url.hostname)}catch{return false}};
function classify(text,phone){const canonical=value=>value.replace(/\D/g,'').replace(/^62/,'0');return text.includes(phone.e164)||text.includes(phone.local)?'DIRECT MATCH':canonical(text).includes(phone.local)?'FORMATTED MATCH':'PARTIAL MATCH'}
export default async function handler(req,res){if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});const key=req.headers['x-forwarded-for']||'anonymous';if(rateLimited(key))return res.status(429).json({error:'Rate limit exceeded'});try{const phone=normalize(req.body?.number);const queries=Array.isArray(req.body?.queries)?[...new Set(req.body.queries)].slice(0,6):[`"${phone.e164}"`];const retrievedAt=new Date().toISOString();let provider,raw=[];
 if(process.env.SERPER_API_KEY){provider='Serper';for(const q of queries){const response=await fetch('https://google.serper.dev/search',{method:'POST',headers:{'Content-Type':'application/json','X-API-KEY':process.env.SERPER_API_KEY},body:JSON.stringify({q,num:10}),signal:AbortSignal.timeout(8000)});if(!response.ok)continue;const data=await response.json();raw.push(...(data.organic||[]).map(item=>({...item,queryVariant:q})));}}
 else if(process.env.BRAVE_API_KEY){provider='Brave Search';for(const q of queries){const url=new URL('https://api.search.brave.com/res/v1/web/search');url.searchParams.set('q',q);const response=await fetch(url,{headers:{Accept:'application/json','X-Subscription-Token':process.env.BRAVE_API_KEY},signal:AbortSignal.timeout(8000)});if(!response.ok)continue;const data=await response.json();raw.push(...(data.web?.results||[]).map(item=>({title:item.title,link:item.url,snippet:item.description,queryVariant:q})));}}
 else return res.status(200).json({provider:'unconfigured',mocked:true,references:[]});
 const seen=new Set(),references=raw.filter(x=>safeUrl(x.link)).filter(x=>{const key=new URL(x.link).origin+new URL(x.link).pathname;if(seen.has(key))return false;seen.add(key);return true}).map((x,i)=>{const text=`${x.title||''} ${x.snippet||''}`,matchType=classify(text,phone);return {id:`PHONE-REF-${i+1}`,title:x.title||'Public reference',url:x.link,snippet:x.snippet||'',source:new URL(x.link).hostname,provider,category:/\.pdf(?:$|\?)/i.test(x.link)?'DOCUMENT':'WEB',queryVariant:x.queryVariant,retrievedAt,matchType,confidence:matchType==='PARTIAL MATCH'?'LOW':'HIGH',claim:matchType==='PARTIAL MATCH'?'UNVERIFIED':'VERIFIED PUBLIC FACT'}});return res.status(200).json({provider,mocked:false,references});
 }catch(error){return res.status(400).json({error:error instanceof Error?error.message:'Invalid request'});}}
