import type {PhoneMetadata,PhoneReference} from '../../types/command';import {comparablePhone,generatePhoneVariants} from './phoneService';
export interface SearchProvider {name:string;search(queries:string[],phone:PhoneMetadata):Promise<PhoneReference[]>}
export interface PhoneMetadataProvider {name:string;lookup(phone:PhoneMetadata):Promise<PhoneMetadata>}
const now=()=>new Date().toISOString();
export function classifyMatch(text:string,phone:PhoneMetadata):Pick<PhoneReference,'matchType'|'confidence'>{if(text.includes(phone.e164)||text.includes(phone.normalizedLocal))return {matchType:'DIRECT MATCH',confidence:'HIGH'};if(comparablePhone(text).includes(phone.normalizedLocal))return {matchType:'FORMATTED MATCH',confidence:'HIGH'};return {matchType:'PARTIAL MATCH',confidence:'LOW'};}
export function deduplicateReferences(items:PhoneReference[]){const seen=new Set<string>();return items.filter(item=>{let key:string;try{const url=new URL(item.url);key=`${url.hostname}${url.pathname}`.toLowerCase().replace(/\/$/,'')}catch{key=item.url.toLowerCase()}const content=`${item.title} ${item.snippet}`.toLowerCase().replace(/\s+/g,' ').trim();const signature=`${key}|${content}`;if(seen.has(signature))return false;seen.add(signature);return true;});}
export class PublicSearchApiProvider implements SearchProvider{name='Configured public search API';async search(queries:string[],phone:PhoneMetadata){const response=await fetch('/api/zona/phone/lookup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({number:phone.e164,queries})});if(!response.ok)throw new Error('Provider pencarian publik tidak tersedia.');const payload=await response.json() as {references:PhoneReference[]};return deduplicateReferences(payload.references||[]);}}
export class SafeMockSearchProvider implements SearchProvider{name='Pegasus safe mock provider';async search(queries:string[],phone:PhoneMetadata){if(phone.e164!=='+6281200000000')return [];const raw=[{title:'Kontak — PT Contoh Digital Indonesia',url:'https://contoh.example/kontak',snippet:`Kontak publik: ${phone.e164} · Jakarta`,category:'BUSINESS' as const},{title:'Direktori mitra publik',url:'https://directory.example/pt-contoh',snippet:`PT Contoh Digital Indonesia — ${phone.normalizedLocal}`,category:'WEB' as const},{title:'Laporan publik contoh',url:'https://docs.example/laporan-contoh.pdf',snippet:`Informasi kontak organisasi ${phone.formattedInternational}`,category:'DOCUMENT' as const}];return raw.map((item,index)=>({...item,id:`PHONE-REF-${index+1}`,source:new URL(item.url).hostname,provider:this.name,queryVariant:queries[index%queries.length],retrievedAt:now(),...classifyMatch(item.snippet,phone),claim:index===0?'VERIFIED PUBLIC FACT' as const:'CO-OCCURRENCE' as const}));}}
export async function searchPublicReferences(phone:PhoneMetadata){const queries=generatePhoneVariants(phone).map(v=>`"${v}"`);const configured=(import.meta as ImportMeta & {env:Record<string,string|undefined>}).env.VITE_PHONE_SEARCH_API_ENABLED==='true';const provider:SearchProvider=configured?new PublicSearchApiProvider():new SafeMockSearchProvider();return {provider:provider.name,references:deduplicateReferences(await provider.search(queries,phone)),queries,mocked:!configured};}
