import type {CommandOutput,ParsedCommand} from '../../types/command';
type Item={id:string;[key:string]:unknown};type Watch=Item&{kind:string;target:string;status:string;createdAt:string};type Evidence=Item&{source:string;sha256:string;createdAt:string;immutable:true;custody:string[];derivativeOf?:string};
const db={watches:[] as Watch[],alerts:[] as Item[],claims:[] as Item[],evidence:[] as Evidence[],audit:[] as string[]};
const now=()=>new Date().toISOString(), id=(p:string,x:Item[])=>`${p}-${String(x.length+1).padStart(3,'0')}`, row=(k:string,v:unknown)=>`${k.padEnd(32,'.')} ${String(v)}`;
const output=(title:string,lines:string[],tone:CommandOutput['tone']='success'):CommandOutput=>({title,lines,tone});const usage=(s:string)=>output('VALIDATION ERROR',[`Usage: ${s}`],'warning');const subject=(a:string[],n=0)=>a.slice(n).join(' ').trim();
async function hash(v:string){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');}
export const getFusionSnapshot=()=>db;
export async function executeFusionCommand(p:ParsedCommand):Promise<CommandOutput|undefined>{const {command,args}=p,a=args[0];db.audit.push(`${now()} ${p.analystId} ${p.raw}`);
 if(command==='dashboard')return output('INTELLIGENCE FUSION DASHBOARD // LIVE',[row('ACTIVE CASES',1),row('OPEN ALERTS',db.alerts.length),row('ENTITIES MONITORED',db.watches.length),row('EVIDENCE COLLECTED',db.evidence.length),row('IDENTITY CONFLICTS',1),row('PENDING REVIEWS',2),row('REPORT STATUS','READY'),row('PROVIDER HEALTH','3 / 3 READY')]);
 if(command==='watch'){if(a==='add'&&args[1]&&subject(args,2)){const w={id:id('WATCH',db.watches),kind:args[1].toUpperCase(),target:subject(args,2),status:'ACTIVE',createdAt:now()};db.watches.push(w);return output('WATCHLIST // MONITOR ACTIVE',[row('WATCH ID',w.id),row('OBJECT',w.kind),row('TARGET',w.target),row('BASELINE','SNAPSHOT-001'),row('PROVIDER','LOCAL MOCK · NO EXTERNAL QUERY')]);}if(a==='list')return output('WATCHLIST',db.watches.length?db.watches.map(w=>`${w.id} ${w.status.padEnd(8)} ${w.kind.padEnd(14)} ${w.target}`):['EMPTY · Run: watch add domain example.com'],'info');const w=db.watches.find(x=>x.id===args[1]);if(!w)return usage(`watch ${a} WATCH-001`);if(a==='pause')w.status='PAUSED';if(a==='resume')w.status='ACTIVE';if(a==='remove')db.watches.splice(db.watches.indexOf(w),1);return output(`WATCH ${w.id} // UPDATED`,[row('TARGET',w.target),row('STATUS',a==='remove'?'REMOVED':w.status)]);}
 if(command==='changes'){const w=db.watches.find(x=>x.target===subject(args,1))??db.watches[0];if(a==='compare')return output('SNAPSHOT COMPARISON',[row('OLD',args[1]),row('NEW',args[2]),row('DIFFERENCES','0 · NO EXTERNAL OBSERVATIONS')]);if(!w)return output('CHANGE DETECTION // EMPTY',['Add a watch to create an authorized baseline.'],'info');if(!db.alerts.length)db.alerts.push({id:'ALERT-001',severity:'LOW',status:'OPEN',watchId:w.id});return output('CHANGE DETECTION // BASELINE EVENT',[row('OLD VALUE','NOT OBSERVED'),row('NEW VALUE','BASELINE CAPTURED'),row('DETECTED UTC',now()),row('SOURCE','LOCAL MOCK PROVIDER'),row('SNAPSHOTS','SNAPSHOT-000 → SNAPSHOT-001'),row('SIGNIFICANCE','LOW'),row('CONFIDENCE','100%'),row('POSSIBLE CAUSE','Initial authorized baseline'),row('ANALYST VERIFICATION','PENDING')]);}
 if(command==='alert'){if(a==='list')return output('ALERT QUEUE',db.alerts.length?db.alerts.map(x=>`${x.id} ${x.severity} ${x.status}`):['NO OPEN ALERTS'],'info');const x=db.alerts.find(x=>x.id===args[1]);if(!x)return usage(`alert ${a} ALERT-001`);if(a==='acknowledge')x.status='ACKNOWLEDGED';if(a==='assign')x.assignee=args[2]?.replace('analyst:','');return output('ALERT // UPDATED',[row('STATUS',x.status),row('ASSIGNEE',x.assignee??'UNASSIGNED')]);}
 if(command==='claim'){if(a==='create'&&subject(args,1)){const c={id:id('CLAIM',db.claims),text:subject(args,1),status:'DRAFT',verdict:'INCONCLUSIVE'};db.claims.push(c);return output('CLAIM WORKSPACE // CREATED',[row('CLAIM ID',c.id),row('CLAIM',c.text),row('STATUS','SOURCES REQUIRED')]);}const c=db.claims.find(x=>x.id===args[1]);if(!c)return usage(`claim ${a??'verify'} CLAIM-001`);return output('CLAIM VERIFICATION // ANALYST REVIEW REQUIRED',[row('CLAIM',c.text),row('VERDICT','INCONCLUSIVE'),row('CONFIDENCE','0%'),row('PRIMARY SOURCES',0),row('SECONDARY SOURCES',0),row('CONTRADICTIONS',0),row('UNRESOLVED QUESTIONS',1),'No verdict generated: two independent cited sources are required.']);}
 if(command==='capture'){const src=subject(args,1)||args[0];if(!src)return usage('capture url https://example.com');const createdAt=now(),e={id:id('E',db.evidence),source:src,sha256:await hash(`${src}|${createdAt}`),createdAt,immutable:true as const,custody:[`${createdAt} ${p.analystId} CAPTURED ORIGINAL`]};db.evidence.push(e);return output('EVIDENCE CAPTURE // PRESERVED',[row('EVIDENCE ID',e.id),row('SHA-256',e.sha256),row('SOURCE URL',e.source),row('COLLECTED UTC',e.createdAt),row('ORIGINAL','IMMUTABLE')]);}
 if(command==='evidence'){const e=db.evidence.find(x=>x.id===args[1]);if(!e)return undefined;if(a==='redact'){const createdAt=now(),d={id:id('E',db.evidence),source:'REDACTED DERIVATIVE',sha256:await hash(`${e.sha256}|${createdAt}`),createdAt,immutable:true as const,derivativeOf:e.id,custody:[`${createdAt} ${p.analystId} DERIVED FROM ${e.id}`]};db.evidence.push(d);return output('REDACTED DERIVATIVE // CREATED',[row('DERIVATIVE ID',d.id),row('ORIGINAL',e.id),row('SHA-256',d.sha256),row('SECRET DISPLAY','REDACTED')]);}return output(`EVIDENCE ${e.id} // ${a.toUpperCase()}`,[row('SHA-256',e.sha256),row('INTEGRITY','VERIFIED'),row('ORIGINAL','READ ONLY'),...e.custody]);}
 if(command==='resolve'&&a==='entity')return output('ENTITY RESOLUTION // CONFIRMATION REQUIRED',[row('CANDIDATES',`${args[1]} ↔ ${args[2]}`),row('MATCHING INDICATORS','NONE INGESTED'),row('CONFLICTING INDICATORS','UNKNOWN'),row('MISSING ATTRIBUTES','SOURCE-BACKED IDENTIFIERS'),row('CONFIDENCE','0%'),row('MERGE CONSEQUENCES','REVIEW REQUIRED')],'warning');
 if(command==='entity'&&a==='merge')return p.flags.review?output('ENTITY MERGE // REVIEW GATE',['Proposal created; no records changed. Senior analyst confirmation required.'],'warning'):output('ENTITY MERGE // BLOCKED',['Automatic merge is prohibited. Use --review.'],'danger');
 if(command==='access')return output('ACCESS CONTROL // EFFECTIVE',[row('ROLE','ANALYST'),row('CASE ACCESS','CASE-2026-001'),row('SENSITIVE FIELDS','MASKED'),row('EXPORT APPROVAL','REQUIRED')]);
 if(command==='audit')return output('IMMUTABLE AUDIT STREAM',db.audit.slice(-20));
 if(command==='exposure')return output('EXPOSURE MONITORING // SAFE OUTPUT',[row('EXPOSURE TYPE','NO VERIFIED FINDING'),row('SECRET DISPLAY','REDACTED'),row('CURRENT STATUS','REQUIRES VERIFICATION'),row('SOURCE','AUTHORIZED PUBLIC INDEX')]);
 if(command==='ask'||command==='ai')return output('EVIDENCE-BOUND AI ASSISTANT',['ANSWER','Insufficient cited workspace evidence.','EVIDENCE','No qualifying citations attached.','CONTRADICTIONS','Not assessable.','CONFIDENCE','0% · INCONCLUSIVE','LIMITATIONS','No facts are inferred without evidence.','RECOMMENDED NEXT STEP','Attach two independent public sources.'],'info');
 if(command==='report'&&a==='generate')return undefined;
 if(['report','collection','source','org','ioc','cve','threat','note','hypothesis','question','lead','playbook','retention','redaction','alias','saved-query','command'].includes(command))return output(`${command.toUpperCase()} // WORKFLOW READY`,[row('ACTION',a??'SHOW'),row('SUBJECT',subject(args,1)||a||'WORKSPACE'),row('PROVENANCE','REQUIRED'),row('DATA MODE','PUBLIC / AUTHORIZED'),row('PROVIDER','LOCAL MOCK · CLEARLY LABELED'),row('ANALYST REVIEW','REQUIRED')],'info');
}
