import type {ConfidenceAssessment,Finding,PivotRecommendation,Relationship,TimelineItem,UsernameComparison,UsernameIntelligenceResult,UsernameMatch,UsernameProfile} from '../../types/command';
import type {IntelligenceProvider,ProviderResult} from '../providers/types';

export function normalizeUsername(input:string){
 const trimmed=input.trim(); if(!trimmed)throw new Error('Username is required.');
 let candidate=trimmed.replace(/^@/,'');
 try{const url=new URL(candidate.includes('://')?candidate:`https://${candidate}`);if(candidate.includes('://'))candidate=url.pathname.split('/').filter(Boolean).at(-1)??'';}catch{/* validated below */}
 candidate=decodeURIComponent(candidate).replace(/^@/,'').replace(/[?#].*$/,'').toLowerCase();
 if(!/^[a-z0-9._-]{2,64}$/.test(candidate))throw new Error('Enter a valid public username, @handle, or public profile URL.'); return candidate;
}
const similarity=(a:string,b:string)=>{const x=a.toLowerCase(),y=b.toLowerCase();if(x===y)return 100;const A=new Set(x.split(/\W+/).filter(Boolean)),B=new Set(y.split(/\W+/).filter(Boolean));const shared=[...A].filter(v=>B.has(v)).length;return Math.round(100*(2*shared/Math.max(1,A.size+B.size)));};
const classify=(score:number):UsernameMatch=>score>=90?'EXACT USERNAME MATCH':score>=75?'STRONG POSSIBLE MATCH':score>=55?'POSSIBLE MATCH':score>=30?'LOW CONFIDENCE':'UNVERIFIED';
const observed='2026-09-05T12:42:00.000Z';
export const publicUsernameProvider:IntelligenceProvider<string,UsernameProfile[]>={name:'Pegasus Indexed Public Sources (Safe Mock)',type:'PUBLIC_INDEX',enabled:true,mocked:true,async search(input):Promise<ProviderResult<UsernameProfile[]>>{const u=normalizeUsername(input);const raw=[
 {platform:'GitHub',url:`https://github.com/${u}`,display:'John Doe',bio:'Open source developer at Example Labs. Security and data tooling.',site:'https://johndoe.example.com',location:'Jakarta, Indonesia',email:'john@johndoe.example.com',org:'Example Labs',score:96},
 {platform:'Dev Community',url:`https://dev.to/${u}`,display:'John Doe',bio:'Developer writing about open source, security, and data.',site:'https://johndoe.example.com',location:'Jakarta',email:'john@johndoe.example.com',org:'Example Labs',score:88},
 {platform:'Public document index',url:`https://example.org/community/authors/${u}`,display:'J. Doe',bio:'Contributor to the public Example community report.',site:'https://example.org',location:'Indonesia',email:undefined,org:'Example Community',score:61}
 ];const data=raw.map((p,i):UsernameProfile=>({id:`UP-${i+1}`,platform:p.platform,profileUrl:p.url,username:i===2?u.replace(/[._-]/g,''):u,displayName:p.display,bio:p.bio,publicWebsite:p.site,publicLocation:p.location,publicDescription:`Indexed public profile observed on ${p.platform}.`,publicEmail:p.email,organization:p.org,lastObserved:observed,source:'Safe deterministic public-index fixture',confidence:p.score,match:classify(p.score),verification:'UNVERIFIED',signals:[{label:'username exact match',score:i===2?18:35,detail:i===2?'Normalized variant':'Exact handle'},{label:'display-name similarity',score:15,detail:p.display},{label:'bio overlap',score:i===2?5:12,detail:'Shared public topic terms'},{label:'linked website',score:p.site.includes('johndoe')?15:4,detail:p.site},{label:'public email',score:p.email?10:0,detail:p.email??'Not observed'},{label:'public domain',score:p.site.includes('johndoe')?5:2,detail:new URL(p.site).hostname},{label:'location overlap',score:8,detail:p.location},{label:'organization overlap',score:p.org==='Example Labs'?8:2,detail:p.org}]}));return {data,provider:this.name,retrievedAt:observed,mocked:true};}};
function compare(left:string,right:string,profiles:UsernameProfile[]):UsernameComparison{const a=normalizeUsername(left),b=normalizeUsername(right),usernameSimilarity=similarity(a.replace(/[._-]/g,''),b.replace(/[._-]/g,''));const domains=[...new Set(profiles.flatMap(p=>p.publicWebsite?[new URL(p.publicWebsite).hostname]:[]))];const emails=[...new Set(profiles.flatMap(p=>p.publicEmail?[p.publicEmail]:[]))];const locations=[...new Set(profiles.flatMap(p=>p.publicLocation?[p.publicLocation]:[]))];const score=Math.round(usernameSimilarity*.4+92*.2+68*.15+(domains.length?100:0)*.1+(emails.length?100:0)*.1+(locations.length?70:0)*.05);return {left:a,right:b,usernameSimilarity,displayNameSimilarity:92,bioSimilarity:68,linkedDomain:domains,publicEmail:emails,locations,commonReferences:['Example Labs','open source','security'],score,conclusion:score>=75?'LIKELY SAME DIGITAL IDENTITY':'INSUFFICIENT EVIDENCE',inference:true};}
export async function createUsernameIntelligence(raw:string,mode:UsernameIntelligenceResult['mode']='lookup',compareWith?:string):Promise<UsernameIntelligenceResult>{const username=normalizeUsername(raw);const search=await publicUsernameProvider.search(username);const profiles=search.data;const now=search.retrievedAt;const findings:Finding[]=profiles.map(p=>({id:`F-${p.id}`,category:'PUBLIC PROFILE',label:`${p.platform} · ${p.match}`,value:p.profileUrl,entityType:'URL',provenance:{id:`SRC-${p.id}`,source:p.source,retrievedAt:p.lastObserved,method:'Public indexed-source lookup',confidence:p.confidence>=80?'HIGH':p.confidence>=55?'MEDIUM':'LOW',sourceUrl:p.profileUrl}}));
 const relationships:Relationship[]=profiles.flatMap(p=>[{id:`R-${p.id}-A`,from:username,to:p.profileUrl,type:'APPEARS_ON',sourceId:`SRC-${p.id}`,confidence:p.confidence,createdAt:now,validationStatus:'UNVERIFIED' as const},...(p.publicWebsite?[{id:`R-${p.id}-L`,from:p.profileUrl,to:p.publicWebsite,type:'LINKS_TO',sourceId:`SRC-${p.id}`,confidence:p.confidence-4,createdAt:now,validationStatus:'UNVERIFIED' as const}]:[]),...(p.organization?[{id:`R-${p.id}-O`,from:p.profileUrl,to:p.organization,type:'PUBLICLY_ASSOCIATED_WITH',sourceId:`SRC-${p.id}`,confidence:p.confidence-8,createdAt:now,validationStatus:'UNVERIFIED' as const}]:[])]);
 const timeline:TimelineItem[]=profiles.map((p,i)=>({id:`UT-${i+1}`,at:p.lastObserved.slice(0,10),type:'PUBLIC OBSERVATION',label:`${p.platform} profile indexed (${p.match})`,sourceId:`SRC-${p.id}`,confidence:p.confidence}));const confidence:ConfidenceAssessment={score:Math.round(profiles.reduce((n,p)=>n+p.confidence,0)/profiles.length),factors:profiles[0].signals.map(s=>({label:`${s.label}: ${s.detail}`,impact:s.score}))};
 const pivots:PivotRecommendation[]=[['INSPECT LINKED DOMAIN','Review website explicitly linked by a public profile.',`domain ${new URL(profiles[0].publicWebsite!).hostname}`],['SEARCH PUBLIC DOCUMENTS','Find indexed documents that mention the handle.',`web "${username}" filetype:pdf`],['SEARCH PUBLIC EMAIL REFERENCE','Correlate only explicitly published email references.',`web "${profiles[0].publicEmail}"`],['OPEN RELATIONSHIP GRAPH','Explore evidence-backed links.',`username graph ${username}`],['COMPARE PROFILE','Test a username variant without assuming identity.',`username compare ${username} ${username.replace(/([a-z])([a-z])$/,'$1_$2')}`],['CREATE TIMELINE','Order public observations.',`username timeline ${username}`]].map((p,i)=>({id:`UPIV-${i+1}`,title:p[0],reason:p[1],expectedOutput:'Public, provenance-linked intelligence',dataSource:search.provider,confidence:85-i*4,estimatedCost:'LOW',caseContext:'CASE-2026-001',command:p[2],status:'READY'}));return {kind:'username',targetType:'username',target:username,normalizedUsername:username,mode,profiles,comparison:mode==='compare'&&compareWith?compare(username,compareWith,profiles):undefined,runId:`USR-${Date.now().toString().slice(-6)}`,startedAt:now,completedAt:now,durationMs:126,stages:[{id:'U1',label:'NORMALIZE',status:'complete'},{id:'U2',label:'PUBLIC INDEX SEARCH',status:'complete'},{id:'U3',label:'CORRELATE',status:'complete'},{id:'U4',label:'BUILD EVIDENCE',status:'complete'}],findings,relationships,timeline,confidence,pivots,mocked:search.mocked,provider:search.provider,disclaimer:'Public/indexed sources only. Matching handles are not proof that profiles belong to the same person; all identity conclusions remain explicit inferences.'};}
