-- PostgreSQL production foundation. IDs are generated by the application.
CREATE TYPE user_status AS ENUM ('ACTIVE','SUSPENDED');
CREATE TYPE case_status AS ENUM ('OPEN','CLOSED','ARCHIVED');
CREATE TYPE case_role AS ENUM ('OWNER','LEAD','ANALYST','VIEWER');

CREATE TABLE users (id text PRIMARY KEY,email text NOT NULL UNIQUE,display_name text NOT NULL,password_hash text NOT NULL,status user_status NOT NULL DEFAULT 'ACTIVE',created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE user_roles (user_id text NOT NULL REFERENCES users(id),role text NOT NULL CHECK (role IN ('ADMIN','SUPERVISOR','ANALYST','VIEWER')),PRIMARY KEY(user_id,role));
CREATE TABLE sessions (id text PRIMARY KEY,user_id text NOT NULL REFERENCES users(id),token_hash text NOT NULL UNIQUE,created_at timestamptz NOT NULL,expires_at timestamptz NOT NULL,last_seen_at timestamptz NOT NULL,revoked_at timestamptz);
CREATE INDEX sessions_user_active_idx ON sessions(user_id,expires_at) WHERE revoked_at IS NULL;

CREATE TABLE cases (id text PRIMARY KEY,title text NOT NULL,description text NOT NULL DEFAULT '',status case_status NOT NULL DEFAULT 'OPEN',created_by text NOT NULL REFERENCES users(id),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE case_members (case_id text NOT NULL REFERENCES cases(id),user_id text NOT NULL REFERENCES users(id),role case_role NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(case_id,user_id));
CREATE TABLE providers (id text PRIMARY KEY,name text NOT NULL,base_url text NOT NULL,capabilities text[] NOT NULL,credential_ref text,enabled boolean NOT NULL DEFAULT false,timeout_ms integer NOT NULL CHECK(timeout_ms>=100),requests_per_minute integer NOT NULL CHECK(requests_per_minute>0));

CREATE TABLE evidence (id text PRIMARY KEY,case_id text NOT NULL REFERENCES cases(id),filename text NOT NULL,media_type text NOT NULL,size bigint NOT NULL CHECK(size>0),sha256 char(64) NOT NULL,storage_key text NOT NULL UNIQUE,encryption_iv text NOT NULL,key_version text NOT NULL,captured_by text NOT NULL REFERENCES users(id),captured_at timestamptz NOT NULL,UNIQUE(case_id,sha256));
CREATE TABLE evidence_custody (id text PRIMARY KEY,evidence_id text NOT NULL REFERENCES evidence(id),actor_id text NOT NULL REFERENCES users(id),action text NOT NULL,occurred_at timestamptz NOT NULL,details jsonb NOT NULL DEFAULT '{}');

CREATE TABLE audit_events (id text PRIMARY KEY,sequence bigint GENERATED ALWAYS AS IDENTITY UNIQUE,occurred_at timestamptz NOT NULL,actor_id text NOT NULL REFERENCES users(id),action text NOT NULL,resource_type text NOT NULL,resource_id text NOT NULL,case_id text REFERENCES cases(id),metadata jsonb NOT NULL DEFAULT '{}',previous_hash char(64) NOT NULL,hash char(64) NOT NULL UNIQUE);
REVOKE UPDATE, DELETE, TRUNCATE ON audit_events FROM PUBLIC;
