import {describe,expect,it} from 'vitest';
import {AuthService,type AuthRepository,type Session,type User} from '../auth/authService';
import {authorize,AuthorizationError,can} from '../auth/authorization';
import {AuditService,type AuditEvent} from '../audit/auditService';
import {EvidenceService,type EvidenceRecord} from '../evidence/evidenceService';
import {ProviderRegistry} from '../providers/providerRegistry';

const user:User={id:'usr-1',email:'analyst@example.test',displayName:'Analyst',status:'ACTIVE',roles:['ANALYST']};

describe('production foundation',()=>{
 it('creates opaque sessions and rejects expired sessions',async()=>{const sessions:Session[]=[];const repository:AuthRepository={findUserByEmail:async email=>email===user.email?user:undefined,getUser:async()=>user,saveSession:async session=>{sessions.push(session)},findSessionByTokenHash:async hash=>sessions.find(item=>item.tokenHash===hash),revokeSession:async(id,at)=>{const found=sessions.find(item=>item.id===id);if(found)found.revokedAt=at}};const auth=new AuthService(repository,{verify:async(_id,password)=>password==='correct'},1000);const loggedIn=await auth.login(user.email,'correct',new Date('2026-01-01T00:00:00Z'));expect(loggedIn.token).not.toBe(loggedIn.session.tokenHash);await expect(auth.authenticate(loggedIn.token,new Date('2026-01-01T00:00:00.500Z'))).resolves.toMatchObject({user});await expect(auth.authenticate(loggedIn.token,new Date('2026-01-01T00:00:02Z'))).rejects.toThrow('expired')});
 it('requires global and case permissions',()=>{const membership={caseId:'case-1',userId:user.id,role:'ANALYST' as const};expect(can(user,'evidence:write',membership)).toBe(true);expect(can(user,'case:admin',membership)).toBe(false);expect(()=>authorize(user,'case:read',{...membership,userId:'other'})).toThrow(AuthorizationError)});
 it('detects mutation in the audit chain',async()=>{const events:AuditEvent[]=[];const audit=new AuditService({latest:async()=>events.at(-1),append:async event=>{events.push(event)},list:async()=>events});await audit.record({occurredAt:'2026-01-01T00:00:00Z',actorId:user.id,action:'CASE_VIEWED',resourceType:'case',resourceId:'case-1',metadata:{ip:'redacted'}});await audit.record({occurredAt:'2026-01-01T00:00:01Z',actorId:user.id,action:'EVIDENCE_READ',resourceType:'evidence',resourceId:'ev-1',metadata:{}});expect(await audit.verify()).toBe(true);events[0].action='MUTATED';expect(await audit.verify()).toBe(false)});
 it('encrypts evidence and verifies it on read',async()=>{const records=new Map<string,EvidenceRecord>();const objects=new Map<string,Uint8Array>();const key=await crypto.subtle.generateKey({name:'AES-GCM',length:256},false,['encrypt','decrypt']);const evidence=new EvidenceService({save:async record=>{records.set(record.id,record)},get:async id=>records.get(id)},{put:async(path,data)=>{objects.set(path,data)},get:async path=>objects.get(path)},{active:async()=>({version:'key-v1',key}),get:async()=>key});const plaintext=new TextEncoder().encode('authorized evidence');const record=await evidence.capture({caseId:'case-1',filename:'note.txt',mediaType:'text/plain',bytes:plaintext,actorId:user.id});expect(objects.get(record.storageKey)).not.toEqual(plaintext);expect((await evidence.read(record.id)).bytes).toEqual(plaintext)});
 it('accepts only allow-listed HTTPS providers',()=>{const registry=new ProviderRegistry(new Set(['api.example.test']));registry.register({id:'domain-1',name:'Domain Provider',capabilities:['DOMAIN'],baseUrl:'https://api.example.test/v1',credentialRef:'secret://providers/domain',enabled:true,timeoutMs:1000,requestsPerMinute:10});expect(registry.list('DOMAIN')).toHaveLength(1);expect(()=>registry.register({id:'bad',name:'Bad',capabilities:['DOMAIN'],baseUrl:'http://api.example.test',enabled:true,timeoutMs:1000,requestsPerMinute:1})).toThrow('allow-listed')});
});
