import type {Finding,FootprintResult,Provenance} from '../../types/command';
export interface ProviderResult<T=unknown>{data:T;provider:string;retrievedAt:string;mocked:boolean}
export interface IntelligenceProvider<I=string,O=unknown>{name:string;type:string;enabled:boolean;mocked:boolean;search(input:I):Promise<ProviderResult<O>>}
export const ALLOWED_MOCK_DOMAINS=['example.com','example.org','example.net'] as const;
export function normalizeDomain(value:string){return value.trim().toLowerCase().replace(/^https?:\/\//,'').split('/')[0].replace(/\.$/,'')}
export function isValidPublicDomain(value:string){const domain=normalizeDomain(value);return /^(?=.{1,253}$)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/.test(domain)&&!/(?:^|\.)(?:localhost|local|internal)$/.test(domain)}
export function createMockFootprint(target:string,kind:FootprintResult['kind'],targetType:FootprintResult['targetType']='domain'):FootprintResult{
 const normalized=targetType==='domain'?normalizeDomain(target):target.trim();const domain=targetType==='domain'?normalized:'example.com';if(targetType==='domain'&&!isValidPublicDomain(domain))throw new Error('Enter a valid public domain name.');
 const now='2026-09-05T12:42:00.000Z';const source=(id:string,method:string):Provenance=>({id,source:'Pegasus Public OSINT Mock',retrievedAt:now,method,confidence:'HIGH',sourceUrl:`https://${domain||'example.com'}`});
 const f=(id:string,category:string,label:string,value:string,entityType:Finding['entityType'],method:string):Finding=>({id,category,label,value,entityType,provenance:source(`SRC-${id.slice(2)}`,method)});
 const findings:Finding[]=[f('F-01','DOMAIN','Registered domain',domain,'DOMAIN','RDAP registration lookup'),f('F-02','DNS','A record','203.0.113.24','IP_ADDRESS','DNS A lookup'),f('F-03','DNS','MX record',`mail.${domain}`,'HOSTNAME','DNS MX lookup'),f('F-04','DNS','NS record',`ns1.${domain}`,'HOSTNAME','DNS NS lookup'),f('F-05','DNS','TXT record','v=spf1 -all',undefined,'DNS TXT lookup'),f('F-06','INFRASTRUCTURE','Autonomous system','AS64500 · Example Networks','ASN','IP-to-ASN correlation'),f('F-07','INFRASTRUCTURE','Hosting provider','Example Networks','ORGANIZATION','Public network registry'),f('F-08','CERTIFICATES','Certificate issuer','Example Trust Services',undefined,'Certificate transparency log'),f('F-09','CERTIFICATES','SAN',`api.${domain}`,'HOSTNAME','Certificate transparency log'),f('F-10','WEB','Public URL',`https://${domain}/about`,'URL','Public web index'),f('F-11','ARCHIVE','Archived reference',`Snapshot · ${domain} · 2025-01-01`,undefined,'Public archive index'),f('F-12','DOCUMENTS','Public document',`https://${domain}/public-report.pdf`,'DOCUMENT','Public document index'),f('F-13','ENTITIES','Organization','Example Organization','ORGANIZATION','Entity extraction')];
 const relationships=[['R-01',domain,'203.0.113.24','RESOLVES_TO','SRC-01'],['R-02',domain,`api.${domain}`,'CERTIFICATE_CONTAINS','SRC-09'],['R-03',domain,'Example Organization','ASSOCIATED_WITH','SRC-13']].map(([id,from,to,type,sourceId],i)=>({id,from,to,type,sourceId,confidence:88-i*4,createdAt:now,validationStatus:'UNVERIFIED' as const}));
 const timeline=[{id:'T-01',at:'2025-01-01',type:'ARCHIVE',label:'First public archive snapshot observed',sourceId:'SRC-11',confidence:90},{id:'T-02',at:'2026-08-18',type:'DNS',label:'Current DNS snapshot observed',sourceId:'SRC-02',confidence:92},{id:'T-03',at:'2026-09-05',type:'ANALYSIS',label:'Digital footprint generated',sourceId:'SRC-13',confidence:100}];
 const pivots=[{id:'P-01',title:'DNS INFRASTRUCTURE',reason:'Domain has resolvable infrastructure records.',expectedOutput:'IP, ASN, provider, and shared infrastructure',dataSource:'Public DNS + network registry',confidence:92,estimatedCost:'LOW' as const,command:`recon domain ${domain}`},{id:'P-02',title:'CERTIFICATE HISTORY',reason:'Certificate contains an additional SAN entry.',expectedOutput:'Current and historical hostnames',dataSource:'Certificate transparency logs',confidence:86,estimatedCost:'LOW' as const,command:`cert ${domain}`},{id:'P-03',title:'PUBLIC DOCUMENTS',reason:'A public document referencing this domain was found.',expectedOutput:'Document metadata and extracted public entities',dataSource:'Public document index',confidence:78,estimatedCost:'MEDIUM' as const,command:`search "site:${domain} filetype:pdf"`},{id:'P-04',title:'RELATIONSHIP GRAPH',reason:`${relationships.length} evidence-backed relationships detected.`,expectedOutput:'Entity relationship graph',dataSource:'Pegasus correlation engine',confidence:84,estimatedCost:'LOW' as const,command:`graph ${domain}`},{id:'P-05',title:'TIMELINE',reason:'Historical observations are available.',expectedOutput:'Chronological infrastructure and archive events',dataSource:'Pegasus timeline fusion',confidence:81,estimatedCost:'LOW' as const,command:`timeline ${domain}`}].map(p=>({...p,caseContext:'CASE-2026-001',status:'READY' as const}));
 const stages=['WHOIS','DNS','CERTIFICATES','INFRASTRUCTURE','WEB REFERENCES','PUBLIC DOCUMENTS','ARCHIVE','ENTITIES','CORRELATION'].map((label,i)=>({id:`S-${i+1}`,label,status:'complete' as const}));
 return {kind,targetType,target:normalized,runId:`RUN-${kind.toUpperCase()}-001`,startedAt:now,completedAt:now,durationMs:2840,stages:kind==='recon'?stages:stages.slice(1),findings,relationships,timeline,confidence:{score:82,factors:[{label:'Direct public sources',impact:30},{label:'Multiple corroborating sources',impact:20},{label:'Recent observations',impact:15},{label:'High source reliability',impact:20},{label:'Inferred relationship',impact:-3}]},pivots};
}
