import type {Finding,MediaEntity,MediaIntelligenceResult,MediaMetadata} from '../../types/command';

const supported=new Set(['image/jpeg','image/png','image/webp','image/tiff','video/mp4','video/quicktime']);
const files=new Map<string,File>();
export const registerMediaFile=(file:File)=>{files.set(file.name,file);return file.name};
export const getRegisteredMedia=()=>[...files.values()];
export const clearRegisteredMedia=()=>files.clear();
const hex=(buffer:ArrayBuffer)=>[...new Uint8Array(buffer)].map(x=>x.toString(16).padStart(2,'0')).join('');
const distance=(a:string,b:string)=>[...BigInt(`0x${a}`).toString(2).padStart(a.length*4,'0')].reduce((n,v,i)=>n+(v!==BigInt(`0x${b}`).toString(2).padStart(b.length*4,'0')[i]?1:0),0);
const bitsToHex=(bits:number[])=>bits.reduce((out,_bit,i)=>out+(i%4===3?parseInt(bits.slice(i-3,i+1).join(''),2).toString(16):''),'');
export function createPerceptualHashes(pixels:Uint8ClampedArray,width:number,height:number){const lum=(x:number,y:number)=>{const i=(y*width+x)*4;return pixels[i]*.299+pixels[i+1]*.587+pixels[i+2]*.114};const values=Array.from({length:64},(_,i)=>lum(Math.min(width-1,Math.floor((i%8+.5)*width/8)),Math.min(height-1,Math.floor((Math.floor(i/8)+.5)*height/8))));const avg=values.reduce((a,b)=>a+b,0)/64;const ahash=bitsToHex(values.map(v=>v>=avg?1:0));const dvalues=Array.from({length:64},(_,i)=>lum(Math.min(width-1,Math.floor((i%8+.5)*width/9)),Math.min(height-1,Math.floor((Math.floor(i/8)+.5)*height/8)))<lum(Math.min(width-1,Math.floor((i%8+1.5)*width/9)),Math.min(height-1,Math.floor((Math.floor(i/8)+.5)*height/8)))?1:0);const dhash=bitsToHex(dvalues);return {ahash,dhash,phash:ahash};}
export function extractEntities(text:string):MediaEntity[]{const specs:[MediaEntity['kind'],RegExp][]=[['EMAIL',/[\w.+-]+@[\w.-]+\.[a-z]{2,}/gi],['URL',/https?:\/\/[^\s]+/gi],['PHONE',/(?:\+?\d[\d ().-]{7,}\d)/g],['DATE',/\b(?:\d{1,2}[/-]){2}\d{2,4}\b/g]];const out:MediaEntity[]=[];for(const [kind,re] of specs)for(const value of text.match(re)??[])out.push({kind,value});for(const email of out.filter(x=>x.kind==='EMAIL'))out.push({kind:'DOMAIN',value:email.value.split('@')[1]});return out.filter((x,i)=>out.findIndex(y=>y.kind===x.kind&&y.value===x.value)===i)}
async function imageData(file:File){const bitmap=await createImageBitmap(file);const canvas=document.createElement('canvas');canvas.width=32;canvas.height=32;const ctx=canvas.getContext('2d',{willReadFrequently:true});if(!ctx)throw new Error('Canvas analysis is unavailable.');ctx.drawImage(bitmap,0,0,32,32);const hashes=createPerceptualHashes(ctx.getImageData(0,0,32,32).data,32,32);const dimensions={width:bitmap.width,height:bitmap.height};bitmap.close();return {hashes,dimensions,canvas};}
async function videoMetadata(file:File):Promise<MediaMetadata>{return new Promise((resolve,reject)=>{const video=document.createElement('video');const url=URL.createObjectURL(file);video.preload='metadata';video.onloadedmetadata=()=>{resolve({mime:file.type,size:file.size,width:video.videoWidth,height:video.videoHeight,duration:video.duration});URL.revokeObjectURL(url)};video.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('Video metadata could not be decoded in this browser.'))};video.src=url})}
const base=(file:File,mode:MediaIntelligenceResult['mode'],metadata:MediaMetadata,sha256:string):MediaIntelligenceResult=>{const now=new Date().toISOString();const provenance={id:`MEDIA-${sha256.slice(0,10)}`,source:'LOCAL FILE / BROWSER',retrievedAt:now,method:'Client-side binary analysis',confidence:'HIGH' as const};const findings:Finding[]=[{id:'media-hash',category:'INTEGRITY',label:'Original SHA-256',value:sha256,provenance},{id:'media-mime',category:'FILE',label:'MIME type',value:metadata.mime,provenance}];return {kind:'media',targetType:'document',target:file.name,fileName:file.name,format:file.name.split('.').pop()?.toUpperCase()??file.type,mode,runId:`MEDIA-${sha256.slice(0,8).toUpperCase()}`,startedAt:now,completedAt:now,durationMs:0,stages:[{id:'preserve',label:'ORIGINAL HASH',status:'complete'},{id:'metadata',label:'METADATA',status:'complete'},{id:'analysis',label:'DERIVATIVE ANALYSIS',status:'complete'}],metadata,hashes:{sha256},ocrText:'',entities:[],findings,relationships:[],timeline:[],confidence:{score:95,factors:[{label:'Binary hash calculated locally',impact:50},{label:'Browser-decoded metadata',impact:30}]},pivots:[],originalPreserved:true,derivativeSeparated:true,disclaimer:'Metadata describes the submitted file. Embedded GPS is not a current or live location. Similarity scores do not establish identity or authenticity.'}};
export async function analyzeMedia(name:string,mode:MediaIntelligenceResult['mode']='analyze',otherName?:string){const file=files.get(name);if(!file)throw new Error(`Select “${name}” with the media picker before analysis.`);if(!supported.has(file.type))throw new Error('Supported formats: JPG, PNG, WEBP, TIFF, MP4, MOV.');const started=performance.now();const sha256=hex(await crypto.subtle.digest('SHA-256',await file.arrayBuffer()));let metadata:MediaMetadata={mime:file.type,size:file.size};let image:{hashes:{ahash:string;dhash:string;phash:string};dimensions:{width:number;height:number};canvas:HTMLCanvasElement}|undefined;if(file.type.startsWith('image/')&&file.type!=='image/tiff'){image=await imageData(file);metadata={...metadata,...image.dimensions}}else if(file.type.startsWith('video/'))metadata=await videoMetadata(file);const result=base(file,mode,metadata,sha256);if(image)result.hashes={...result.hashes,...image.hashes};if(mode==='ocr'&&image){const Detector=(globalThis as typeof globalThis&{TextDetector?:new()=>{detect:(source:ImageBitmapSource)=>Promise<{rawValue:string}[]>}}).TextDetector;if(!Detector)throw new Error('OCR is not available in this browser. Use a browser with the Text Detection API enabled.');const detected=await new Detector().detect(image.canvas);result.ocrText=detected.map(x=>x.rawValue).join('\n').trim();result.entities=extractEntities(result.ocrText)}if(mode==='compare'){const other=files.get(otherName??'');if(!other)throw new Error(`Select “${otherName??'comparison file'}” with the media picker first.`);if(!image||!other.type.startsWith('image/')||other.type==='image/tiff')throw new Error('Image comparison requires two browser-decodable images.');const second=await imageData(other);const hashDistance=distance(image.hashes.dhash,second.hashes.dhash);const similarity=Math.round((1-hashDistance/64)*100);const sameRatio=Math.abs((metadata.width!/metadata.height!)-(second.dimensions.width/second.dimensions.height))<.02;result.comparison={target:other.name,similarity,hashDistance,metadataDifferences:[file.type===other.type?'MIME matches':`MIME: ${file.type} → ${other.type}`,file.size===other.size?'File size matches':`File size: ${file.size} → ${other.size} bytes`],dimensionDifference:`${metadata.width}×${metadata.height} → ${second.dimensions.width}×${second.dimensions.height}`,possibleRecompression:similarity>80&&sha256!==hex(await crypto.subtle.digest('SHA-256',await other.arrayBuffer())),possibleCrop:sameRatio&&similarity>=45&&similarity<92,disclaimer:'Heuristic indicators only. This comparison does not claim identity, manipulation, or that an image is fake.'}}
 result.durationMs=Math.round(performance.now()-started);return result;
}
