export type CommandDefinition = { name:string; aliases?:string[]; usage:string; description:string; category:'CORE'|'SEARCH'|'NETWORK'|'IDENTITY'|'ANALYSIS'|'CASE' };
export const commandRegistry: CommandDefinition[] = [
 {name:'help',usage:'help [command]',description:'Show command reference',category:'CORE'}, {name:'clear',aliases:['cls'],usage:'clear',description:'Clear console output',category:'CORE'}, {name:'status',usage:'status',description:'Show workspace and provider status',category:'CORE'}, {name:'history',usage:'history',description:'Show execution history',category:'CORE'},
 {name:'search',usage:'search "keyword" [--source web] [--limit 20]',description:'Search authorized public sources',category:'SEARCH'}, {name:'web',usage:'web "keyword"',description:'Search indexed public web',category:'SEARCH'}, {name:'news',usage:'news "keyword"',description:'Search public news sources',category:'SEARCH'},
 {name:'domain',usage:'domain example.test',description:'Build a domain intelligence profile',category:'NETWORK'}, {name:'dns',usage:'dns example.test',description:'Inspect DNS records',category:'NETWORK'}, {name:'ip',usage:'ip 203.0.113.24',description:'Inspect a reserved or authorized IP',category:'NETWORK'}, {name:'asn',usage:'asn 64500',description:'Inspect an autonomous system',category:'NETWORK'}, {name:'whois',usage:'whois example.test',description:'Query authorized registration data',category:'NETWORK'}, {name:'url',usage:'url https://example.test',description:'Inspect a public URL safely',category:'NETWORK'},
 {name:'person',usage:'person "Name"',description:'Search authorized person records',category:'IDENTITY'}, {name:'organization',aliases:['company'],usage:'organization "Organization"',description:'Research an organization',category:'IDENTITY'}, {name:'username',usage:'username handle',description:'Search public username references',category:'IDENTITY'}, {name:'email',usage:'email analyst@example.test',description:'Inspect an authorized email indicator',category:'IDENTITY'}, {name:'phone',usage:'phone "+62..."',description:'Inspect authorized public phone data',category:'IDENTITY'},
 {name:'entity',usage:'entity find "keyword"',description:'Find or create workspace entities',category:'ANALYSIS'}, {name:'graph',usage:'graph entity:123',description:'Open relationship graph',category:'ANALYSIS'}, {name:'timeline',usage:'timeline entity:123',description:'Open investigation timeline',category:'ANALYSIS'}, {name:'geo',usage:'geo "location"',description:'Open approximate geospatial context',category:'ANALYSIS'}, {name:'investigate',usage:'investigate domain example.test',description:'Run defensive intelligence workflow',category:'ANALYSIS'},
 {name:'case',usage:'case open CASE-2026-001',description:'Manage investigation context',category:'CASE'}, {name:'evidence',usage:'evidence add result:456',description:'Add evidence with custody log',category:'CASE'}, {name:'report',usage:'report generate CASE-2026-001',description:'Generate investigation report',category:'CASE'}
];
export const resolveCommand=(input:string)=>commandRegistry.find(({name,aliases})=>name===input||aliases?.includes(input));
