export type CommandDefinition = { name:string; aliases?:string[]; usage:string; description:string; category:'CORE'|'SEARCH'|'NETWORK'|'IDENTITY'|'ANALYSIS'|'CASE'|'FUSION'|'GOVERNANCE' };
export const commandRegistry: CommandDefinition[] = [
 {name:'help',usage:'help [command]',description:'Show command reference',category:'CORE'}, {name:'clear',aliases:['cls'],usage:'clear',description:'Clear console output',category:'CORE'}, {name:'status',usage:'status',description:'Show workspace and provider status',category:'CORE'}, {name:'history',usage:'history',description:'Show execution history',category:'CORE'},
 {name:'search',usage:'search "keyword" [--source web] [--limit 20]',description:'Search authorized public sources',category:'SEARCH'}, {name:'web',usage:'web "keyword"',description:'Search indexed public web',category:'SEARCH'}, {name:'news',usage:'news "keyword"',description:'Search public news sources',category:'SEARCH'},
 {name:'footprint',usage:'footprint domain example.com',description:'Map a public digital footprint',category:'ANALYSIS'}, {name:'recon',usage:'recon domain example.com',description:'Run the domain recon pipeline',category:'ANALYSIS'}, {name:'pivot',usage:'pivot entity E-129',description:'Recommend evidence-led next steps',category:'ANALYSIS'},
 {name:'media',usage:'media analyze <file> | media compare <a> <b>',description:'Analyze or compare selected media evidence',category:'ANALYSIS'}, {name:'image',usage:'image metadata|ocr|hash <file>',description:'Inspect image metadata, text, and perceptual hashes',category:'ANALYSIS'},
 {name:'domain',usage:'domain example.com',description:'Build a Domain Infrastructure Intelligence V2 profile',category:'NETWORK'}, {name:'infra',usage:'infra example.com',description:'Summarize current domain infrastructure',category:'NETWORK'}, {name:'infra-history',usage:'infra-history example.com',description:'Detect infrastructure changes over time',category:'NETWORK'}, {name:'subdomains',usage:'subdomains example.com',description:'Discover public-source hostnames',category:'NETWORK'}, {name:'dns',usage:'dns example.com',description:'Inspect DNS records',category:'NETWORK'}, {name:'ip',usage:'ip 203.0.113.24',description:'Inspect a reserved or authorized IP',category:'NETWORK'}, {name:'asn',usage:'asn 64500',description:'Inspect an autonomous system',category:'NETWORK'}, {name:'whois',usage:'whois example.com',description:'Query authorized registration data',category:'NETWORK'}, {name:'cert',usage:'cert example.com',description:'Inspect public certificate records',category:'NETWORK'}, {name:'archive',usage:'archive example.com',description:'Inspect public archive references',category:'NETWORK'}, {name:'url',usage:'url https://example.com',description:'Inspect a public URL safely',category:'NETWORK'},
 {name:'person',usage:'person create|search|profiles|verify|content|timeline|impersonation|watch|evidence|report',description:'Persona Intelligence public-data workflow',category:'IDENTITY'}, {name:'profile',usage:'profile inspect|compare|verify|reject|review|impersonation-check <id>',description:'Review public profile candidates',category:'IDENTITY'}, {name:'impersonation',usage:'impersonation report|evidence|export <profile>',description:'Build an analyst-reviewed impersonation evidence package',category:'IDENTITY'}, {name:'organization',aliases:['company'],usage:'organization "Organization"',description:'Research an organization',category:'IDENTITY'}, {name:'username',usage:'username discover|search|variations|exact|reused|compare|platforms|timeline|attach <handle>',description:'Correlate indexed public username presence',category:'IDENTITY'}, {name:'email',usage:'email [lookup|footprint|web|documents|graph|timeline|pivot|exposure] <email>',description:'Analyze public email exposure and domain correlation',category:'IDENTITY'}, {name:'phone',usage:'phone [lookup|footprint|web|documents|graph|timeline|evidence|pivot] <number>',description:'Analyze Indonesian phone metadata and indexed public references',category:'IDENTITY'},
 {name:'entity',usage:'entity find "keyword"',description:'Find or create workspace entities',category:'ANALYSIS'}, {name:'graph',usage:'graph entity:123',description:'Open relationship graph',category:'ANALYSIS'}, {name:'timeline',usage:'timeline entity:123',description:'Open investigation timeline',category:'ANALYSIS'}, {name:'geo',usage:'geo "location"',description:'Open approximate geospatial context',category:'ANALYSIS'}, {name:'investigate',usage:'investigate domain example.test',description:'Run defensive intelligence workflow',category:'ANALYSIS'},
 {name:'document',usage:'document <analyze|entities|metadata|links|timeline> <file>',description:'Analyze PDF, Office, text, or HTML evidence',category:'ANALYSIS'},
 {name:'case',usage:'case open CASE-2026-001',description:'Manage investigation context',category:'CASE'}, {name:'evidence',usage:'evidence hash|verify|custody|snapshot|duplicate-check|redact|export E-100',description:'Preserve immutable evidence',category:'CASE'}, {name:'report',usage:'report create|preview|validate|redact|export <id>',description:'Build provenance-controlled reports',category:'CASE'},
 ...[
 ['dashboard','dashboard [alerts|providers|activity]','Fusion operations dashboard'],['watch','watch add|list|show|pause|resume|remove','Authorized public monitoring'],['changes','changes <type> <target> [--since 30d]','Compare public snapshots'],['alert','alert list|acknowledge|assign','Manage change alerts'],['claim','claim create|verify|sources|contradictions|timeline|verdict|attach|export','Verify claims with citations'],['source','source inspect|score|history|compare|corroborate|archive|flag','Source reliability'],['resolve','resolve entity|search|duplicates|conflicts','Entity resolution review'],['org','org profile|registry|leadership|affiliates|procurement|sanctions|litigation|news|compare|risk','Organization intelligence'],['ioc','ioc inspect|enrich|relationships|timeline|reputation|export','Passive IOC intelligence'],['cve','cve [affected|mitigations] CVE-ID','Public CVE intelligence'],['threat','threat campaign "Name"','Campaign intelligence'],['exposure','exposure check|monitor|findings|show|remediate|verify-fixed','Authorized exposure monitoring'],['collection','collection create|add|analyze|duplicates|contradictions|entities|timeline|citations|search|summarize|export','Batch documents'],['capture','capture url|page|screenshot <url>','Preserve public evidence'],['ask','ask case|evidence <id> "question"','Evidence-bound assistant'],['ai','ai contradictions|gaps|pivots|hypotheses|brief|explain-confidence','Evidence-bound analysis']
 ].map(([name,usage,description])=>({name,usage,description,category:'FUSION' as const})),
 ...[['note','note add|link|assign'],['hypothesis','hypothesis test|evidence|contradict'],['question','question open|resolve'],['lead','lead promote LEAD-001'],['playbook','playbook list|show|run|status|resume|export']].map(([name,usage])=>({name,usage,description:'Structured investigation workflow',category:'CASE' as const})),
 ...[['access','access status|request'],['audit','audit show|user|export'],['retention','retention show|set'],['redaction','redaction preview E-100']].map(([name,usage])=>({name,usage,description:'Privacy, RBAC, and audit control',category:'GOVERNANCE' as const})),
 ...[['alias','alias create <name> "commands"'],['saved-query','saved-query create|run'],['command','command validate|explain "command"']].map(([name,usage])=>({name,usage,description:'Safe command palette workflow',category:'CORE' as const}))
];
export const resolveCommand=(input:string)=>commandRegistry.find(({name,aliases})=>name===input||aliases?.includes(input));
