import type { CommandOutput, DomainProfile, ParsedCommand } from '../../types/command'; import { commandRegistry } from './commandRegistry';
const mockDomain=(domain:string):DomainProfile=>({domain,registrar:'Example Registry (fictional)',created:'2021-03-14',updated:'2026-08-18',expiry:'2027-03-14',nameservers:['ns1.zona.example','ns2.zona.example'],records:[{type:'A',value:'203.0.113.24'},{type:'AAAA',value:'2001:db8::24'},{type:'MX',value:'mail.garudateknologi.example'},{type:'TXT',value:'v=spf1 -all'}],related:[{type:'IP ADDRESS',label:'203.0.113.24'},{type:'ASN',label:'AS64500 · Example Networks'},{type:'CERTIFICATE',label:'CN=garudateknologi.example'},{type:'ORGANIZATION',label:'PT Garuda Teknologi Nusantara'}],reliability:'B',confidence:'2'});
export async function executeCommand(parsed:ParsedCommand):Promise<CommandOutput>{
 const {command,args}=parsed;
 if(command==='help'){const lines=commandRegistry.reduce<string[]>((all,item,index,array)=>{if(index===0||array[index-1].category!==item.category) all.push('',item.category); all.push(`  ${item.usage.padEnd(34)} ${item.description}`); return all;},[]);return {title:'AUTHORIZED COMMAND REFERENCE',tone:'info',lines};}
 if(command==='status') return {title:'SYSTEM STATUS // NOMINAL',tone:'success',lines:['Gateway ................ CONNECTED','Authorized providers .... 7 / 8 ONLINE','Audit stream ............ ACTIVE','Current case ............ CASE-2026-001','Classification .......... INTERNAL']};
 if(command==='history') return {title:'QUERY HISTORY',tone:'info',lines:['Open the execution history tray below for commands, status, provider, and duration.']};
 if(command==='clear') return {title:'CLEAR',tone:'info',lines:[]};
 if(command==='case'&&args[0]==='open') return {title:'CASE CONTEXT UPDATED',tone:'success',lines:[`${args[1]??'CASE-2026-001'} is now the active investigation.`]};
 if(command==='investigate'){const target=args.at(-1)??'garudateknologi.example'; const result=mockDomain(target); return {title:'INVESTIGATION PIPELINE // COMPLETE',tone:'success',lines:['DOMAIN .................... FOUND','DNS ....................... ANALYZED','IP ........................ RESOLVED','ASN ....................... CORRELATED','PUBLIC SOURCES ............ SEARCHED','ENTITIES .................. 12','RELATIONSHIPS ............. 31','TIMELINE .................. GENERATED'],result};}
 if(command==='domain'){const target=args[0]; if(!target) return {title:'VALIDATION ERROR',tone:'warning',lines:['Usage: domain example.test']}; const result=mockDomain(target); return {title:'DOMAIN INTELLIGENCE COMPLETE',tone:'success',lines:[`Profile created for ${target}.`,`4 DNS records and ${result.related.length} related indicators found.`],result};}
 if(['graph','timeline','geo'].includes(command)) return {title:`${command.toUpperCase()} VIEW READY`,tone:'info',lines:[`Analysis workspace prepared for ${args[0]??'the active case'}.`,`Phase 1 preview uses safe fictional data.`]};
 return {title:`${command.toUpperCase()} SEARCH COMPLETE`,tone:'success',lines:[`Authorized mock provider searched for “${args.join(' ')||'current context'}”.`,'3 fictional results returned · no live personal data accessed.']};
}
