import type {DomainIntelligenceResult,DomainMode,Finding,Provenance} from '../../types/command';
import {isValidPublicDomain,normalizeDomain} from '../providers/types';
type Payload={provider:string;retrievedAt:string;durationMs:number;records:{a:string[];aaaa:string[];mx:{exchange:string;priority:number}[];ns:string[];txt:string[][];rdap?:{handle?:string;status?:string[];events?:{eventAction:string;eventDate:string}[];links?:{href:string}[]}|null};errors:string[]};
export async function createDomainIntelligence(input:string,mode:DomainMode):Promise<DomainIntelligenceResult>{
 const domain=normalizeDomain(input);if(!isValidPublicDomain(domain))throw new Error('Enter a valid public domain name.');
 const response=await fetch(`/api/zona/domain/collect?domain=${encodeURIComponent(domain)}`,{headers:{accept:'application/json'}});if(!response.ok)throw new Error(response.status===429?'Domain provider rate limited.':'Domain provider unavailable; no collection was recorded as successful.');
 const data=await response.json() as Payload;const source=(id:string,url:string,method:string):Provenance=>({id,source:data.provider,sourceUrl:url,retrievedAt:data.retrievedAt,method,confidence:'HIGH'});
 const dnsSource=source('SRC-DNS',`https://dns.google/resolve?name=${encodeURIComponent(domain)}`,'Passive DNS lookup'),rdapSource=source('SRC-RDAP',`https://rdap.org/domain/${encodeURIComponent(domain)}`,'RDAP lookup');
 const finding=(id:string,category:string,label:string,value:string,entityType:Finding['entityType'],provenance:Provenance):Finding=>({id,category,label,value,entityType,provenance});
 const ips=[...data.records.a,...data.records.aaaa];const findings:Finding[]=[...ips.map((v,i)=>finding(`F-IP-${i}`,'DNS',isIPv6(v)?'AAAA record':'A record',v,'IP_ADDRESS',dnsSource)),...data.records.ns.map((v,i)=>finding(`F-NS-${i}`,'DNS','NS record',v,'HOSTNAME',dnsSource)),...data.records.mx.map((v,i)=>finding(`F-MX-${i}`,'DNS','MX record',`${v.priority} ${v.exchange}`,'HOSTNAME',dnsSource))];
 if(data.records.rdap?.handle)findings.unshift(finding('F-RDAP','RDAP','Registry handle',data.records.rdap.handle,'DOMAIN',rdapSource));
 const relationships=ips.map((ip,i)=>({id:`R-${i}`,from:domain,to:ip,type:'RESOLVES_TO',sourceId:dnsSource.id,confidence:95,createdAt:data.retrievedAt,validationStatus:'UNVERIFIED' as const}));
 const events=data.records.rdap?.events??[];const timeline=events.map((e,i)=>({id:`T-${i}`,at:e.eventDate,type:'RDAP',label:e.eventAction,sourceId:rdapSource.id,confidence:90}));
 const partial=data.errors.length>0;return {kind:'domain-v2',targetType:'domain',target:domain,mode,runId:`RUN-DOMAIN-${Date.now()}`,startedAt:data.retrievedAt,completedAt:new Date().toISOString(),durationMs:data.durationMs,stages:[{id:'DNS',label:partial?'DNS (PARTIAL)':'DNS',status:'complete'},{id:'RDAP',label:data.records.rdap?'RDAP':'RDAP (UNAVAILABLE)',status:'complete'}],findings,relationships,timeline,confidence:{score:findings.length?90:0,factors:[{label:'Direct passive provider response',impact:findings.length?90:0}]},pivots:[],summary:{currentIps:ips,historicalIps:[],nameservers:data.records.ns,mailInfrastructure:data.records.mx.map(x=>`${x.priority} ${x.exchange}`),certificates:[],subdomains:[],asn:'',hostingProvider:'',technology:[],archivedHostnames:[]},changes:[],risks:[],mocked:false,provider:data.provider,disclaimer:`Passive public DNS/RDAP only. ${partial?`Unavailable record types: ${data.errors.join(', ')}. No result does not prove absence.`:'No result does not prove absence.'}`};
}
const isIPv6=(value:string)=>value.includes(':');
