import type {DomainChange,DomainIntelligenceResult,DomainMode,DomainRisk,Finding,Provenance} from '../../types/command';
import {isValidPublicDomain,normalizeDomain} from '../providers/types';
const observedAt='2026-09-05T12:42:00.000Z';
export async function createDomainIntelligence(input:string,mode:DomainMode):Promise<DomainIntelligenceResult>{
 const domain=normalizeDomain(input);if(!isValidPublicDomain(domain))throw new Error('Enter a valid public domain name.');
 const provenance=(id:string,source:string,method:string,url:string,confidence:Provenance['confidence']='HIGH'):Provenance=>({id,source,retrievedAt:observedAt,method,confidence,sourceUrl:url});
 const rdap=provenance('SRC-RDAP','IANA RDAP bootstrap (safe mock)','RDAP registration lookup',`https://rdap.org/domain/${domain}`),dns=provenance('SRC-DNS','Authoritative DNS snapshot (safe mock)','DNS A/NS/MX/TXT query',`https://${domain}`),ct=provenance('SRC-CT','Certificate Transparency log (safe mock)','CT log search',`https://crt.sh/?q=${encodeURIComponent(domain)}`),registry=provenance('SRC-RIR','Regional Internet Registry (safe mock)','IP-to-ASN lookup','https://www.iana.org/assignments/as-numbers/as-numbers.xhtml'),archive=provenance('SRC-ARCHIVE','Public web archive index (safe mock)','Archived hostname search',`https://web.archive.org/web/*/${domain}`,'MEDIUM'),threat=provenance('SRC-TI','Configured threat-intel adapter (safe mock)','Reputation lookup',`https://${domain}`,'MEDIUM');
 const summary={currentIps:['203.0.113.24'],historicalIps:['198.51.100.17','203.0.113.24'],nameservers:[`ns1.${domain}`,`ns2.${domain}`],mailInfrastructure:[`10 mail.${domain}`],certificates:[`CN=${domain} · Example Trust · expires 2026-11-30`],subdomains:[`api.${domain}`,`mail.${domain}`,`www.${domain}`],asn:'AS64500 · Example Networks',hostingProvider:'Example Networks',technology:['nginx','React'],archivedHostnames:[`legacy.${domain}`,`www.${domain}`]};
 const f=(id:string,category:string,label:string,value:string,entityType:Finding['entityType'],p:Provenance):Finding=>({id,category,label,value,entityType,provenance:p});
 const findings:Finding[]=[f('F-DOM','WHOIS/RDAP','Registration','Created 2020-01-15 · active','DOMAIN',rdap),...summary.currentIps.map((x,i)=>f(`F-IP${i}`,'DNS','Current IP',x,'IP_ADDRESS',dns)),...summary.nameservers.map((x,i)=>f(`F-NS${i}`,'DNS','Nameserver',x,'HOSTNAME',dns)),f('F-MX','MX','Mail exchanger',summary.mailInfrastructure[0],'HOSTNAME',dns),f('F-TXT','TXT','SPF policy','v=spf1 -all',undefined,dns),...summary.subdomains.map((x,i)=>f(`F-SUB${i}`,'SUBDOMAIN','Observed hostname',x,'HOSTNAME',ct)),f('F-ASN','ASN','Network',summary.asn,'ASN',registry),f('F-HOST','HOSTING','Provider',summary.hostingProvider,'ORGANIZATION',registry),f('F-TECH','TECHNOLOGY','Observed stack',summary.technology.join(', '),undefined,dns),f('F-ARC','ARCHIVE','Archived hostname',summary.archivedHostnames.join(', '),'HOSTNAME',archive),f('F-DOC','PUBLIC DOCUMENTS','Indexed document',`https://${domain}/public-report.pdf`,'DOCUMENT',archive),f('F-CERT','CERTIFICATE','Leaf certificate',summary.certificates[0],undefined,ct)];
 const change=(id:string,at:string,type:DomainChange['type'],before:string,after:string,p:Provenance):DomainChange=>({id,at,type,before,after,provenance:p});
 const changes=[change('CH-1','2025-04-12','IP CHANGE','198.51.100.17','203.0.113.24',dns),change('CH-2','2025-08-03','HOSTING CHANGE','Example Legacy Hosting','Example Networks',registry),change('CH-3','2026-07-22','CERTIFICATE CHANGE','Example Trust serial 01','Example Trust serial 02',ct),change('CH-4','2026-08-18','NEW SUBDOMAIN','—',`api.${domain}`,ct)];
 const risk=(id:string,signal:DomainRisk['signal'],severity:DomainRisk['severity'],score:number,explanation:string,evidence:string,p:Provenance):DomainRisk=>({id,signal,severity,score,explanation,evidence,provenance:p});
 const risks=[risk('RS-1','INFRASTRUCTURE CHURN','MEDIUM',45,'Two material infrastructure changes were observed; this can be operationally normal but warrants validation.','IP and hosting changed in 2025.',registry),risk('RS-2','SHORT CERTIFICATE AGE','LOW',15,'The certificate is recent, but its lifetime is consistent with automated rotation.','First observed 2026-07-22.',ct),risk('RS-3','THREAT-INTEL REPUTATION','LOW',0,'No negative reputation was returned; absence of a hit is not proof of safety.','No matching reputation record.',threat)];
 const relationships=[{id:'R-DI',from:domain,to:summary.currentIps[0],type:'RESOLVES_TO',sourceId:dns.id,confidence:96,createdAt:observedAt,validationStatus:'VALIDATED' as const},{id:'R-IA',from:summary.currentIps[0],to:summary.asn,type:'ANNOUNCED_BY',sourceId:registry.id,confidence:92,createdAt:observedAt,validationStatus:'VALIDATED' as const},{id:'R-AH',from:summary.asn,to:summary.hostingProvider,type:'OPERATED_BY',sourceId:registry.id,confidence:88,createdAt:observedAt,validationStatus:'UNVERIFIED' as const},{id:'R-DS',from:domain,to:`api.${domain}`,type:'HAS_SUBDOMAIN',sourceId:ct.id,confidence:90,createdAt:observedAt,validationStatus:'UNVERIFIED' as const},{id:'R-DC',from:domain,to:summary.certificates[0],type:'PRESENTS_CERTIFICATE',sourceId:ct.id,confidence:94,createdAt:observedAt,validationStatus:'VALIDATED' as const}];
 const stages=['WHOIS / RDAP','DNS','MX','NS','TXT','CERTIFICATE TRANSPARENCY','SUBDOMAIN','IP','ASN','HOSTING','TECHNOLOGY','ARCHIVE','PUBLIC DOCUMENTS','GRAPH','CORRELATION'].map((label,i)=>({id:`S-${i+1}`,label,status:'complete' as const}));
 return {kind:'domain-v2',targetType:'domain',target:domain,mode,runId:`RUN-DOMAIN-${domain.toUpperCase()}`,startedAt:observedAt,completedAt:observedAt,durationMs:1840,stages,findings,relationships,timeline:changes.map(c=>({id:`T-${c.id}`,at:c.at,type:c.type,label:`${c.before} → ${c.after}`,sourceId:c.provenance.id,confidence:90})),confidence:{score:88,factors:[{label:'Every result has source and retrieval time',impact:35},{label:'DNS and registry corroboration',impact:28},{label:'Historical observations may be incomplete',impact:-10}]},pivots:[],summary,changes,risks,mocked:true,provider:'Pegasus Domain Infrastructure V2 · safe mock adapters',disclaimer:'Passive public-source intelligence only. Historical datasets may be incomplete; findings and risks require analyst validation.'};
}
