import type {Finding,ParsedCommand,PersonPurpose,PersonaCandidate,PersonaIntelligenceResult,Provenance} from '../../types/command';
import {personaProviders} from './providers';

export const PERSON_PURPOSES:PersonPurpose[]=['self-audit','authorized-investigation','fraud-or-impersonation-review','professional-due-diligence','public-figure-research','missing-account-recovery','brand-or-reputation-monitoring'];
export const AUTHORIZATION_NOTICE=['AUTHORIZED PUBLIC-DATA WORKFLOW ONLY','Use only public, consented, or lawfully authorized information.','Do not use this workspace for stalking, intimidation, discrimination, doxing, credential theft, or unauthorized surveillance.'];
export const PERSON_ACTIONS=['create','authorize','scope','add-alias','add-username','add-organization','add-location','add-url','show','edit','archive','search','profiles','candidates','coverage','verify','conflicts','confidence','content','topics','hashtags','links','mentions','statements','content-search','language','narrative','interactions','mentions-graph','collaborators','organizations','communities','interaction','timeline','impersonation','watch','alerts','changes','unwatch','claims','claim-create','controversies','corrections','official-statements','source-comparison','evidence','report','aliases','usernames','emails','graph'] as const;

type RecordBase={id:string;caseId:string;source:string;sourceUrl:string;collectionTime:string;publicationTime?:string;confidence:number;verificationStatus:string;analystStatus:string;provenance:string;sensitivityLevel:'PUBLIC'|'RESTRICTED';retentionPolicy:string};
export interface PersonRecord extends RecordBase {name:string;purpose:PersonPurpose;authorization:'PENDING'|'AUTHORIZED';scopeConfirmed:boolean;aliases:string[];usernames:string[];organizations:string[];locations:string[];urls:string[];candidates:PersonaCandidate[]}
export interface PersonaDataModel {Person:PersonRecord;PersonAlias:RecordBase;PersonSearchSeed:RecordBase;SocialPlatform:RecordBase;SocialProvider:RecordBase;SocialProfile:RecordBase;ProfileCandidate:RecordBase;ProfileMatchIndicator:RecordBase;ProfileConflict:RecordBase;UsernameObservation:RecordBase;EmailPublicReference:RecordBase;PublicContent:RecordBase;PublicMention:RecordBase;PublicAffiliation:RecordBase;ProfileSnapshot:RecordBase;ImpersonationFinding:RecordBase;PersonTimelineEvent:RecordBase;PersonEvidence:RecordBase;AnalystDecision:RecordBase;AuthorizationRecord:RecordBase;ProviderRun:RecordBase;AuditEvent:RecordBase}

const people=new Map<string,PersonRecord>();
const audit:string[]=[];
const now=()=>new Date().toISOString();
const nextId=()=>`PERSON-${String(people.size+1).padStart(3,'0')}`;
function base(id:string,caseId:string):RecordBase{return {id,caseId,source:'ANALYST INPUT',sourceUrl:'local://analyst-input',collectionTime:now(),confidence:100,verificationStatus:'UNVERIFIED',analystStatus:'REVIEW REQUIRED',provenance:'Manual, lawfully supplied seed',sensitivityLevel:'PUBLIC',retentionPolicy:'CASE POLICY'}}
function log(action:string,id:string){const event=`AUDIT-${String(audit.length+1).padStart(5,'0')} · ${now()} · ${action} · ${id}`;audit.push(event);return event}
const pipeline=['IDENTITY SEEDS','WEB REFERENCES','FACEBOOK','INSTAGRAM','THREADS','X / TWITTER','TIKTOK','LINKEDIN','YOUTUBE','GITHUB','GOOGLE PUBLIC','EMAIL REFERENCES','TELEGRAM PUBLIC','REDDIT','PROFESSIONAL PROFILES','PUBLIC DOCUMENTS','PROFILE CORRELATION','IMPERSONATION CHECK','TIMELINE','EVIDENCE'];
function providerCards(person:PersonRecord,selected?:string[]):PersonaCandidate[]{return personaProviders.filter(p=>!selected||selected.includes('all')||selected.includes(p.id)).map((p,i)=>({id:`PROFILE-${person.id}-${String(i+1).padStart(2,'0')}`,platform:p.label,category:p.category,platformStatus:p.resultStatus,username:'—',displayName:'No verified public profile',bio:p.status==='UNAVAILABLE'?'Provider unavailable. This is not evidence that an account does not exist.':'Automated discovery is not configured. Use the public indexed-search handoff or attach lawful evidence manually.',accountType:'PROVIDER SEARCH STATE',platformVerified:false,lastObserved:now(),matchingIndicators:[],conflictingIndicators:['Identity has not been independently verified'],confidence:0,status:'UNRESOLVED',source:'Pegasus provider registry',sourceUrl:p.safeSearchUrl(person.name),collectedAt:now(),verificationStatus:'ANALYST REVIEW REQUIRED'}));}
function result(person:PersonRecord,mode:string,auditEventId:string):PersonaIntelligenceResult {const provenance:Provenance={id:`SRC-${person.id}`,source:'Analyst-supplied public seed',sourceUrl:person.urls[0],retrievedAt:person.collectionTime,method:'MANUAL INPUT',confidence:'HIGH'};const findings:Finding[]=[...person.aliases.map((value,i)=>({id:`ALIAS-${i+1}`,category:'PUBLIC ALIAS',label:'Analyst supplied',value,entityType:'PERSON' as const,provenance})),...person.usernames.map((value,i)=>({id:`USER-${i+1}`,category:'USERNAME',label:'Known public username',value,entityType:'USERNAME' as const,provenance}))];const pivot=(id:string,title:string,reason:string,command:string)=>({id,title,reason,expectedOutput:'Public candidates with provenance',dataSource:'Configured public providers',confidence:50,estimatedCost:'LOW' as const,caseContext:person.caseId,command,status:'READY' as const});return {kind:'persona',targetType:'person',target:person.name,personId:person.id,purpose:person.purpose,authorization:person.authorization,scopeConfirmed:person.scopeConfirmed,mode,aliases:person.aliases,usernames:person.usernames,candidates:person.candidates,runId:`RUN-PERSON-${String(Date.now()).slice(-6)}`,startedAt:person.collectionTime,completedAt:now(),durationMs:0,stages:pipeline.map((label,i)=>({id:`stage-${i}`,label,status:'complete' as const})),findings,relationships:person.candidates.filter(c=>c.confidence>0).map(c=>({id:`REL-${c.id}`,from:person.id,to:c.id,type:'POSSIBLE PROFILE',sourceId:c.id,confidence:c.confidence,createdAt:c.collectedAt,validationStatus:'UNVERIFIED'})),timeline:[],confidence:{score:person.candidates.length?Math.max(...person.candidates.map(c=>c.confidence)):0,factors:[{label:'No candidate is automatically confirmed',impact:0},{label:person.authorization==='AUTHORIZED'?'Authorization recorded':'Authorization pending',impact:person.authorization==='AUTHORIZED'?10:-20}]},pivots:[pivot('PIVOT-USERNAME','USERNAME PIVOT','Review only supplied or publicly observed usernames',`person usernames ${person.id}`),pivot('PIVOT-EMAIL','PUBLIC EMAIL REFERENCES','Exact public-reference search; no account enumeration',`person emails ${person.id}`),pivot('PIVOT-ORG','ORGANIZATION PIVOT','Review public professional affiliations',`person organizations ${person.id}`),pivot('PIVOT-DOC','PUBLIC DOCUMENT PIVOT','Review attributable public documents',`person evidence ${person.id}`),pivot('PIVOT-IMPERSONATION','IMPERSONATION REVIEW','Compare unresolved candidates without automatic reporting',`person impersonation ${person.id}`)],auditEventId,provider:'PUBLIC PROVIDER REGISTRY',mocked:false,disclaimer:`${AUTHORIZATION_NOTICE.join(' ')} Inbox access, account enumeration, password-reset probing, OTP, private endpoints, biometric face recognition, and automatic identity merges are not permitted.`} }
export function executePersona(parsed:ParsedCommand,caseId='CASE-2026-001'):{title:string;tone:'success'|'info'|'warning';lines:string[];result?:PersonaIntelligenceResult}|undefined {
 if(parsed.command!=='person')return;
 const [actionRaw,...rest]=parsed.args;
 if(actionRaw&&!PERSON_ACTIONS.includes(actionRaw as typeof PERSON_ACTIONS[number])&&!/^PERSON-\d+$/i.test(actionRaw)){const id=nextId();const person:PersonRecord={...base(id,caseId),name:parsed.args.join(' '),purpose:'self-audit',authorization:'AUTHORIZED',scopeConfirmed:true,aliases:[],usernames:[],organizations:[],locations:[],urls:[],candidates:[]};person.candidates=providerCards(person);people.set(id,person);const event=log('PUBLIC PERSON SEARCH',id);return {title:'PERSONA INTELLIGENCE // PUBLIC SOCIAL SEARCH COMPLETE',tone:'success',lines:[`TARGET ......................... ${person.name}`,'TARGET TYPE .................... PERSON','SEARCH PURPOSE ................. SELF AUDIT',`PLATFORMS REQUESTED ............. ${person.candidates.length}`,`PROVIDERS UNAVAILABLE ........... ${person.candidates.filter(c=>c.platformStatus==='PROVIDER UNAVAILABLE').length}`,'PROFILE CANDIDATES .............. 0','ANALYST REVIEW REQUIRED ......... YES','No profile has been automatically confirmed.'],result:result(person,'social',event)}}
 const action=PERSON_ACTIONS.includes(actionRaw as typeof PERSON_ACTIONS[number])?actionRaw:'search';
 if(action==='create'){const name=rest.join(' ').trim();const purpose=String(parsed.flags.purpose??'');if(!name||!PERSON_PURPOSES.includes(purpose as PersonPurpose))return {title:'AUTHORIZATION REQUIRED',tone:'warning',lines:[...AUTHORIZATION_NOTICE,'Usage: person create "Name" --purpose self-audit','A permitted purpose is required; sensitive seed data is not required.']};const id=nextId();const person:PersonRecord={...base(id,caseId),name,purpose:purpose as PersonPurpose,authorization:'PENDING',scopeConfirmed:false,aliases:[],usernames:[],organizations:[],locations:[],urls:[],candidates:[]};people.set(id,person);const event=log('PERSON CREATE',id);return {title:'PERSONA INTELLIGENCE // PERSON CREATED',tone:'success',lines:[...AUTHORIZATION_NOTICE,`SUBJECT ........................ ${id}`,`SEARCH PURPOSE ................. ${purpose.toUpperCase().replaceAll('-',' ')}`,'AUTHORIZATION .................. PENDING','SCOPE CONFIRMATION ............. REQUIRED',`AUDIT EVENT .................... ${event}`],result:result(person,'create',event)}}
 const id=rest.find(v=>/^PERSON-\d+$/i.test(v))??(action==='search'&&/^PERSON-\d+$/i.test(actionRaw)?actionRaw:undefined);const person=id?people.get(id.toUpperCase()):undefined;
 if(!person)return {title:'PERSON NOT FOUND',tone:'warning',lines:[...AUTHORIZATION_NOTICE,'Create a subject first: person create "Name" --purpose self-audit']};
 if(action==='authorize'){person.authorization='AUTHORIZED';person.scopeConfirmed=true;const event=log('AUTHORIZATION CONFIRMED',person.id);return {title:'PERSONA INTELLIGENCE // AUTHORIZED',tone:'success',lines:[...AUTHORIZATION_NOTICE,`SUBJECT ........................ ${person.id}`,`CASE ........................... ${String(parsed.flags.case??caseId)}`,'SCOPE .......................... PUBLIC, CONSENTED, OR LAWFULLY AUTHORIZED DATA',`AUDIT EVENT .................... ${event}`],result:result(person,action,event)}}
 if(['add-alias','add-username','add-organization','add-location','add-url'].includes(action)){const value=rest.filter(v=>v!==person.id).join(' ');if(!value)return {title:'VALIDATION ERROR',tone:'warning',lines:[`Usage: person ${action} ${person.id} <value>`]};const field={'add-alias':'aliases','add-username':'usernames','add-organization':'organizations','add-location':'locations','add-url':'urls'}[action] as 'aliases'|'usernames'|'organizations'|'locations'|'urls';person[field].push(value);const event=log(action.toUpperCase(),person.id);return {title:'PERSON SEED UPDATED',tone:'success',lines:[`${field.toUpperCase()} ....................... ${value}`,`AUDIT EVENT .................... ${event}`],result:result(person,action,event)}}
 const event=log(action.toUpperCase(),person.id);if(['search','verify','content','watch','report'].includes(action)&&(!person.scopeConfirmed||person.authorization!=='AUTHORIZED'))return {title:'AUTHORIZATION & SCOPE REQUIRED',tone:'warning',lines:[...AUTHORIZATION_NOTICE,`Run: person authorize ${person.id} --case ${caseId}`,`Then review: person scope ${person.id} --edit`],result:result(person,action,event)};
 if(['search','profiles','coverage'].includes(action)){const requested=String(parsed.flags.platform??'all').split(',');person.candidates=providerCards(person,requested)}
 return {title:action==='search'?'PERSONA INTELLIGENCE // SEARCH COMPLETE':`PERSONA INTELLIGENCE // ${action.toUpperCase()}`,tone:'success',lines:[`SUBJECT ........................ ${person.id}`,`SEARCH PURPOSE ................. ${person.purpose.toUpperCase().replaceAll('-',' ')}`,'PUBLIC PROFILE CANDIDATES ...... 0','CONFIRMED PROFILES ............. 0','REVIEW REQUIRED ................ YES','No candidate has been automatically confirmed.','PROVIDER RESTRICTED providers must be searched officially and attached manually.',`AUDIT EVENT .................... ${event}`],result:result(person,action,event)};
}
export function resetPersonaStore(){people.clear();audit.length=0}
