import {AlertTriangle,CheckCircle2,FileText,Network,Search,ShieldCheck,UserRoundSearch} from 'lucide-react';
import {useNavigate} from 'react-router-dom';

const sections=['Person Overview','Search Seeds','Profile Candidates','Confirmed Profiles','Usernames','Content','Mentions','Interactions','Organizations','Timeline','Impersonation','Evidence','Reports'];
const providers=['Instagram','Facebook','X','Threads','TikTok','LinkedIn','YouTube','GitHub','GitLab','Reddit','Medium','Mastodon'];
const badges=['CONFIRMED','HIGH CONFIDENCE','MEDIUM CONFIDENCE','LOW CONFIDENCE','UNRESOLVED','REJECTED','POSSIBLE IMPERSONATION','PRIVACY REDACTED'];
export function PersonaWorkspace(){const navigate=useNavigate();return <main className="flex min-h-0 flex-1 flex-col overflow-hidden p-3 md:p-4">
 <header className="mb-3 flex shrink-0 flex-wrap items-center gap-4 rounded-lg border border-cyan-300/15 bg-[#08131e] px-5 py-4"><div className="grid h-10 w-10 place-items-center rounded border border-cyan-300/30 bg-cyan-300/[.07]"><UserRoundSearch className="text-cyan-300" size={20}/></div><div><p className="text-[8px] font-semibold tracking-[.28em] text-cyan-300">PEGASUS ZONA // PERSONA INTELLIGENCE v0.3.0</p><h1 className="mt-1 text-sm font-semibold text-white">PUBLIC SOCIAL MEDIA OSINT</h1></div><div className="ml-auto rounded border border-emerald-300/15 bg-emerald-300/[.04] px-3 py-2 text-[8px] tracking-widest text-emerald-300"><ShieldCheck className="mr-2 inline" size={12}/> AUDIT LOG ACTIVE</div></header>
 <div className="mb-3 rounded border border-amber-300/20 bg-amber-300/[.035] px-4 py-3"><p className="flex items-center gap-2 text-[9px] font-semibold tracking-widest text-amber-200"><AlertTriangle size={13}/> AUTHORIZED PUBLIC-DATA WORKFLOW ONLY</p><p className="mt-1 text-[9px] text-slate-500">Use only public, consented, or lawfully authorized information. No private accounts, authentication bypass, sensitive inference, precise live location, or automated contact.</p></div>
 <div className="grid min-h-0 flex-1 overflow-hidden rounded-lg border border-white/[.07] bg-[#08111b]/90 xl:grid-cols-[210px_1fr_280px]">
  <aside className="persona-desktop-panel console-scroll overflow-y-auto border-r border-white/[.06] p-3"><p className="px-2 pb-2 text-[8px] tracking-[.2em] text-slate-600">PERSON WORKSPACE</p>{sections.map((s,i)=><button key={s} className={`mb-0.5 flex w-full items-center gap-2 rounded px-2.5 py-2 text-left text-[9px] ${i===0?'border border-cyan-300/15 bg-cyan-300/[.06] text-cyan-200':'text-slate-500 hover:bg-white/[.03]'}`}><span className="w-4 font-mono text-[7px] text-slate-700">{String(i+1).padStart(2,'0')}</span>{s}</button>)}</aside>
  <section className="console-scroll overflow-y-auto p-5"><div className="flex items-start justify-between"><div><p className="text-[8px] tracking-[.2em] text-cyan-400">PERSON OVERVIEW / NO ACTIVE SUBJECT</p><h2 className="mt-2 text-xl text-white">Start with minimal, non-sensitive seeds.</h2><p className="mt-2 max-w-xl text-[10px] leading-5 text-slate-500">Create a person, select a lawful purpose, and confirm case scope before any provider can run. Candidates always remain unresolved until an analyst decides.</p></div><Search className="text-cyan-400/30" size={32}/></div>
   <div className="mt-5 grid gap-2 md:grid-cols-3"><button onClick={()=>navigate('/zona')} className="rounded border border-cyan-300/20 bg-cyan-300/[.05] p-4 text-left"><p className="text-[9px] font-semibold text-cyan-200">CREATE PERSON</p><code className="mt-2 block text-[8px] text-slate-500">person create "Name" --purpose self-audit</code></button><div className="rounded border border-white/[.07] p-4"><p className="text-[9px] text-slate-300">AUTHORIZE SCOPE</p><p className="mt-2 text-[8px] leading-4 text-slate-600">Bind authorization to the active Case before collection.</p></div><div className="rounded border border-white/[.07] p-4"><p className="text-[9px] text-slate-300">ANALYST REVIEW</p><p className="mt-2 text-[8px] leading-4 text-slate-600">No automatic identity merge or platform report.</p></div></div>
   <p className="mt-6 text-[8px] tracking-[.2em] text-slate-500">PUBLIC PROVIDER REGISTRY</p><div className="mt-2 grid grid-cols-2 gap-2 md:grid-cols-4">{providers.map((p,i)=><div key={p} className="rounded border border-white/[.06] p-3"><div className="flex items-center justify-between"><span className="text-[9px] text-slate-300">{p}</span>{i>7?<AlertTriangle size={11} className="text-amber-300"/>:<CheckCircle2 size={11} className="text-emerald-300"/>}</div><p className={`mt-2 text-[7px] ${i>7?'text-amber-300':'text-emerald-400'}`}>{i>7?'MANUAL / RESTRICTED':'ADAPTER READY'}</p></div>)}</div>
   <div className="mt-6 grid gap-3 md:grid-cols-2"><div className="rounded border border-white/[.07] p-4"><p className="flex items-center gap-2 text-[8px] tracking-widest text-cyan-300"><Network size={12}/> INTEGRATED OBJECTS</p><p className="mt-3 text-[9px] leading-5 text-slate-500">Case · Entity · SHA-256 Evidence · Public Timeline · Labeled Interaction Graph · Watchlist · Alert · Redacted Report</p></div><div className="rounded border border-white/[.07] p-4"><p className="flex items-center gap-2 text-[8px] tracking-widest text-cyan-300"><FileText size={12}/> EVIDENCE POLICY</p><p className="mt-3 text-[9px] leading-5 text-slate-500">Originals are immutable. Snapshots retain source URL, collection/publication time, confidence, provenance, sensitivity, and retention.</p></div></div>
  </section>
  <aside className="persona-desktop-panel console-scroll overflow-y-auto border-l border-white/[.06] p-4"><p className="text-[8px] tracking-[.2em] text-slate-500">IDENTITY CONTROL</p><div className="mt-3 rounded border border-amber-300/15 bg-amber-300/[.025] p-3"><p className="text-[8px] text-amber-200">AUTHORIZATION STATUS</p><p className="mt-2 text-lg font-semibold text-white">NOT STARTED</p><p className="mt-1 text-[8px] text-slate-600">Purpose and scope are mandatory.</p></div>{['Identity confidence','Matching indicators','Conflicts','Source provenance','Privacy warnings','Analyst notes','Recommended pivots'].map(x=><div key={x} className="mt-2 rounded border border-white/[.06] px-3 py-2.5 text-[8px] text-slate-500">{x}<span className="float-right text-slate-700">—</span></div>)}<p className="mt-5 text-[8px] tracking-widest text-slate-600">STATUS BADGES</p><div className="mt-2 flex flex-wrap gap-1.5">{badges.map((b,i)=><span key={b} className={`rounded border px-2 py-1 text-[7px] ${i===6?'border-amber-300/20 text-amber-200':i===7?'border-violet-300/20 text-violet-200':'border-cyan-300/15 text-cyan-300'}`}>{b}</span>)}</div></aside>
 </div></main>}
