import type {PlatformCategory,PlatformResultStatus} from '../../types/command';
export type PersonaProviderStatus='AVAILABLE'|'RESTRICTED'|'UNAVAILABLE';
export interface PersonaProvider {id:string;label:string;category:PlatformCategory;status:PersonaProviderStatus;resultStatus:PlatformResultStatus;officialApi:boolean;authorizationRequirement:'NONE'|'API KEY'|'MANUAL REVIEW';availability:string;safeSearchUrl:(query:string)=>string;search(input:{name:string;username?:string;signal:AbortSignal}):Promise<readonly unknown[]>}
const definitions:[string,string,PlatformCategory,PersonaProviderStatus][]=[
 ['facebook','Facebook','SOCIAL','RESTRICTED'],['instagram','Instagram','SOCIAL','RESTRICTED'],['threads','Threads','SOCIAL','RESTRICTED'],['x','X / Twitter','SOCIAL','RESTRICTED'],['tiktok','TikTok','SOCIAL','RESTRICTED'],['linkedin','LinkedIn','PROFESSIONAL','RESTRICTED'],['pinterest','Pinterest','SOCIAL','RESTRICTED'],['tumblr','Tumblr','SOCIAL','RESTRICTED'],['youtube','YouTube','CREATOR','RESTRICTED'],['spotify','Spotify / Podcasts','CREATOR','RESTRICTED'],['soundcloud','SoundCloud','CREATOR','RESTRICTED'],['github','GitHub','PROFESSIONAL','RESTRICTED'],['gitlab','GitLab','PROFESSIONAL','RESTRICTED'],['stackoverflow','Stack Overflow','PROFESSIONAL','RESTRICTED'],['orcid','ORCID','PROFESSIONAL','RESTRICTED'],['reddit','Reddit','COMMUNITY','RESTRICTED'],['medium','Medium','COMMUNITY','RESTRICTED'],['substack','Substack','COMMUNITY','RESTRICTED'],['telegram','Telegram Public','COMMUNITY','RESTRICTED'],['google','Google Public Ecosystem','GOOGLE','RESTRICTED'],['gmail','Email & Google Public Footprint','EMAIL','RESTRICTED'],['scholar','Google Scholar','PROFESSIONAL','RESTRICTED'],['bluesky','Bluesky','SOCIAL','UNAVAILABLE'],['mastodon','Mastodon','SOCIAL','UNAVAILABLE'],['twitch','Twitch','CREATOR','UNAVAILABLE'],['discord','Discord Public','COMMUNITY','UNAVAILABLE'],['researchgate','ResearchGate','PROFESSIONAL','UNAVAILABLE'],['academia','Academia.edu','PROFESSIONAL','UNAVAILABLE'],['behance','Behance','PROFESSIONAL','UNAVAILABLE'],['dribbble','Dribbble','PROFESSIONAL','UNAVAILABLE']];
const hosts:Record<string,string>={x:'x.com',stackoverflow:'stackoverflow.com',orcid:'orcid.org',google:'google.com',gmail:'google.com',scholar:'scholar.google.com',telegram:'t.me',spotify:'open.spotify.com',discord:'discord.com',academia:'academia.edu'};
export const personaProviders:PersonaProvider[]=definitions.map(([id,label,category,status])=>({id,label,category,status,resultStatus:status==='UNAVAILABLE'?'PROVIDER UNAVAILABLE':'MANUAL REVIEW REQUIRED',officialApi:false,authorizationRequirement:status==='UNAVAILABLE'?'MANUAL REVIEW':'NONE',availability:status,safeSearchUrl:query=>`https://www.google.com/search?q=${encodeURIComponent(`site:${hosts[id]??id+'.com'} "${query}"`)}`,async search(){return []}}));
export const PROVIDER_RESTRICTED='PROVIDER RESTRICTED\n\nAutomated collection is unavailable for this platform.\nUse the official platform search or manually attach lawfully obtained public evidence.';
export function safePublicUrl(raw:string){const url=new URL(raw);if(url.protocol!=='https:')throw new Error('Only HTTPS public evidence URLs are accepted.');const host=url.hostname.toLowerCase();if(host==='localhost'||host.endsWith('.local')||/^127\.|^10\.|^192\.168\.|^169\.254\./.test(host))throw new Error('Private or local destinations are blocked.');url.username='';url.password='';url.hash='';return url.toString()}
