import {useEffect,useState} from 'react';import {Activity,Database,LockKeyhole,Radio,ShieldCheck} from 'lucide-react';import {Navigate,Route,Routes,useLocation} from 'react-router-dom';import {Sidebar} from './components/layout/Sidebar';import {Topbar} from './components/layout/Topbar';import {CommandConsole} from './modules/command/components/CommandConsole';import {CommandPalette} from './modules/command/components/CommandPalette';import {HistoryTray} from './modules/command/components/HistoryTray';import {ResultPanel} from './modules/command/components/ResultPanel';import {useWorkspaceStore} from './stores/workspaceStore';

function OperationsStrip(){const {activeCase,history}=useWorkspaceStore();const successful=history.filter(item=>item.status==='SUCCESS').length;return <div className="mb-3 hidden shrink-0 items-center gap-4 rounded-lg border border-white/[.06] bg-[#08121c]/75 px-4 py-2.5 lg:flex">
  <div className="flex items-center gap-2"><span className="status-beacon"/><div><p className="text-[8px] font-semibold tracking-[.2em] text-emerald-300">OPERATIONS NOMINAL</p><p className="text-[8px] text-slate-600">All defensive systems monitored</p></div></div>
  <div className="h-7 w-px bg-white/[.06]"/>
  <div className="flex items-center gap-2 text-[9px] text-slate-500"><ShieldCheck size={13} className="text-cyan-400"/><span>CASE</span><b className="font-mono text-slate-300">{activeCase}</b></div>
  <div className="ml-auto flex items-center gap-5 text-[8px] tracking-wider text-slate-600"><span className="flex items-center gap-1.5"><Database size={12}/> {successful} VERIFIED RUNS</span><span className="flex items-center gap-1.5"><Radio size={12} className="text-emerald-400"/> 7 SOURCES READY</span><span className="flex items-center gap-1.5"><LockKeyhole size={12} className="text-cyan-400"/> AUDIT ACTIVE</span><span className="flex items-center gap-1.5 text-cyan-300"><Activity size={12}/> LIVE WORKSPACE</span></div>
 </div>}
function CommandCenter(){const [draft,setDraft]=useState('');const [mobilePane,setMobilePane]=useState<'command'|'workspace'>('command');const chooseCommand=(value:string)=>{setDraft(value);setMobilePane('command')};return <><main className="flex min-h-0 flex-1 flex-col p-3 md:p-4"><OperationsStrip/><div className="mb-2 flex shrink-0 rounded border border-white/[.06] xl:hidden"><button onClick={()=>setMobilePane('command')} className={`flex-1 py-2 text-[9px] tracking-widest ${mobilePane==='command'?'bg-cyan-300/[.07] text-cyan-300':'text-slate-600'}`}>COMMAND</button><button onClick={()=>setMobilePane('workspace')} className={`flex-1 py-2 text-[9px] tracking-widest ${mobilePane==='workspace'?'bg-cyan-300/[.07] text-cyan-300':'text-slate-600'}`}>INTELLIGENCE WORKSPACE</button></div><div className="command-shell grid h-full min-h-0 overflow-hidden rounded-lg border border-white/[.07] bg-[#08111b]/80 shadow-glow xl:grid-cols-[45%_55%]"><div className={`${mobilePane==='command'?'block':'hidden'} min-h-0 border-b border-white/[.06] xl:block xl:border-b-0 xl:border-r`}><CommandConsole draft={draft} setDraft={setDraft}/></div><div className={`${mobilePane==='workspace'?'block':'hidden'} min-h-0 xl:block`}><ResultPanel onCommand={chooseCommand}/></div></div></main><div className="hidden xl:block"><HistoryTray/></div><CommandPalette onSelect={chooseCommand}/></>}
function Placeholder(){const location=useLocation();const title=location.pathname.split('/').at(-1)?.replaceAll('-',' ');return <main className="grid flex-1 place-items-center p-8 text-center"><div><p className="text-[10px] tracking-[.3em] text-cyan-400">PEGASUS ZONA / PHASE ROADMAP</p><h1 className="mt-3 text-2xl capitalize text-white">{title}</h1><p className="mt-2 max-w-md text-sm text-slate-500">Module route is connected and reserved for a subsequent implementation phase. Return to Command Center to use the operational Phase 1 workflow.</p></div></main>}
export default function App(){useEffect(()=>{document.documentElement.classList.add('dark')},[]);return <div className="relative flex h-screen overflow-hidden bg-zona-950 text-slate-200"><div className="tactical-grid pointer-events-none absolute inset-0 opacity-40"/><Sidebar/><div className="relative flex min-w-0 flex-1 flex-col"><Topbar/><Routes><Route path="/zona" element={<CommandCenter/>}/><Route path="/zona/:module" element={<Placeholder/>}/><Route path="*" element={<Navigate to="/zona" replace/>}/></Routes></div></div>}
